### PR TITLE
add some space below the conversation (like chatGPT)

### PR DESCRIPTION
**Pull request by fontanierh**
Reverts dust-tt/dust#2048

simply re-adding it

### CODE REVIEW

**Review by spolu — CHANGES_REQUESTED** [review]
Works great but I think we want to deactivate it on mobile?

Screenshot from 2023-10-11 14-30-21

**Comment by spolu** [comment]
This is the same view on mobile while streaming ^ which is when it's particularly weird

**Comment by fontanierh** [comment]
Ah yes good catch. thanks !

**Comment by fontanierh** [comment]
Removed on mobile

**Review by spolu — APPROVED** [review]

**Pull request merged**
