### PR TITLE
[front] - refactor: make description folder optional

### LINKED ISSUE #7362: Folder creation description
When we create a folder, the description field is not mentioned as mandatory, still it fails when you try to save. We should make it clearer that description is required!

Image

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

This PR aims at making the "description" field of a folder optional. This is iso with what we currently have.

**References:**
 - https://github.com/dust-tt/dust/issues/7362

## Risk

Low

## Deploy Plan

Deploy `front`

### CODE REVIEW

**Review by Fraggle — APPROVED** [review]
FYI : I have a PR (blocked for a bug) that refactor this code (extract actions in hooks etc..)

**Comment by JulesBelveze** [comment]
@Fraggle want me to wait for your PR to be merged?

**Comment by Fraggle** [comment]
> @Fraggle want me to wait for your PR to be merged?

No go for it, i have a f****g bug that I can't figure out.

**Review by Fraggle — COMMENTED** [review]
(sorry I though i had "approve")

**Pull request merged**
