### PR TITLE
Data Source new UI

### PR DESCRIPTION
**Pull request by lasryaric**
There is two commits:
- one that implements the UI changes requested by @gabhubert (see attached screenshots) and another one that replaces all mention of "data source" by "Data Source" in the code base.
I would recommend to review them separately.

Screen Shot 2023-05-15 at 21 19 38
Screen Shot 2023-05-15 at 21 23 35

### CODE REVIEW

**Comment by spolu** [comment]
Haven’t reviewed the code. But based on the screenshot we probably want to update the Apps pane as well to align the positioning of the “New XX” button.

I personally prefer it up top as even if the hierarchy is not perfect it’s the main call to action for now on each page.

The fact that it’s not aligned with the “Connect” buttons is also weird visually. Maybe try to align it right?

**Comment by gabhubert** [comment]
Not sure I agree on the hierarchy bit @spolu, it’s still a pretty short
page people should be able to find it?
Agree on right-align for consistency

**Comment by lasryaric** [comment]
I also think having the create button under the appropriate section makes
more sense.

I will align it on the right side and some more screenshots tomorrow.

**Comment by spolu** [comment]
On hierarchy I was hypothesizing that this was the motivation here. But I agree it does not really matter given the structure of the page. If there is no specific motivation for moving the button down I'm personally in favor of keeping it up as a clear call to action since this is the only clickable button with a real effect unless you are not a "paid" user (aka ~everyone)

**Comment by lasryaric** [comment]
Just to clarify my stand on this topic: I think it makes more sense to have the "New Data Source" button under the section "Uploaded Data Sources".
In general, I find product which respect the hierarchy of information much more intuitive to use. I am actually a fan of that concept too :)

**Comment by spolu** [comment]
Also given how the conversation is going, maybe we want to split the PR in two PRs. One for wording on which we are all aligned I think. And one for the UI?

**Pull request closed without merging**
