### PR TITLE
Datasource setting to autmatically select it for Assistant queries

### PR DESCRIPTION
**Pull request by philipperolet**
See details [here](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1692610875267989)

### CODE REVIEW

**Comment by philipperolet** [comment]
Also the tailwind config linting error popped back and is fixed here again

**Comment by spolu** [comment]
Can you post screnshots of the new and config screen of data sources? :pray:

**Review by spolu — DISMISSED** [review]
LGTM but awaiting screenshots to validate UI :+1:

**Review by spolu — APPROVED** [review]
LGTM

**Pull request merged**
