### PR TITLE
fix: don't redirect to sso page for superuser auth

### PR DESCRIPTION
**Pull request by fontanierh**
## Description

Currently, poke is broken for ssoEnforced workspace, as navigating to the page redirects to the SSO page.

### CODE REVIEW

**Review by flvndvd — APPROVED** [review]
I guess this situation would only occur if our workspace had SSO enforced, right?

**Comment by fontanierh** [comment]
@flvndvd just when going to a workpaces' poke page if they have ssoEnforced

**Comment by flvndvd** [comment]
> @flvndvd just when going to a workpaces' poke page if they have ssoEnforced

Ah yeah 🙃.

**Comment by spolu** [comment]
Thanks for handling 👍

**Pull request merged**
