### PR TITLE
[front] - fix: data source agent usage query

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

The previous query used to count the number of assistants using a data source was also counting "archived" assistants. 

This new PR retrieves the associated `agentConfiguration` to only keep "active" assistants.

## Risk

The query is a bit more complex requiring a couple of joins

## Deploy Plan

Deploy `front`

### CODE REVIEW

**Review by spolu — APPROVED** [review]

**Review by spolu — COMMENTED** [review]
Can we try to get the generated SQL and profile it just to make sure given how complex the query is indeed?

**Comment by JulesBelveze** [comment]
<details>
  <summary>SQL query:</summary>

```sql
SELECT
  "dataSource"."id" AS "dataSourceId",
  COUNT("dataSource"."id") AS "count"
FROM
  "agent_data_source_configurations" AS "agent_data_source_configuration"
  INNER JOIN "data_sources" AS "dataSource" ON "agent_data_source_configuration"."dataSourceId" = "dataSource"."id"
  AND "dataSource"."workspaceId" = 1
  AND "dataSource"."connectorProvider" IS NULL
  INNER JOIN "agent_retrieval_configurations" AS "agent_retrieval_configuration" ON "agent_data_source_configuration"."retrievalConfigurationId" = "agent_retrieval_configuration"."id"
  INNER JOIN "agent_configurations" AS "agent_retrieval_configuration->agent_configuration" ON "agent_retrieval_configuration"."agentConfigurationId" = "agent_retrieval_configuration->agent_configuration"."id"
  AND "agent_retrieval_configuration->agent_configuration"."status" = 'active'
GROUP BY
  "dataSource"."id";
  ```

</details>

<details>
<summary> Explain analyze </summary>

```
 Finalize GroupAggregate  (cost=8703.44..8714.08 rows=119 width=12) (actual time=28.404..30.986 rows=18 loops=1)
   Group Key: "dataSource".id
   ->  Gather Merge  (cost=8703.44..8712.54 rows=70 width=12) (actual time=28.396..30.973 rows=20 loops=1)
         Workers Planned: 1
         Workers Launched: 1
         ->  Partial GroupAggregate  (cost=7703.43..7704.65 rows=70 width=12) (actual time=24.301..24.311 rows=10 loops=2)
               Group Key: "dataSource".id
               ->  Sort  (cost=7703.43..7703.60 rows=70 width=4) (actual time=24.280..24.285 rows=12 loops=2)
                     Sort Key: "dataSource".id
                     Sort Method: quicksort  Memory: 25kB
                     Worker 0:  Sort Method: quicksort  Memory: 25kB
                     ->  Nested Loop  (cost=178.52..7701.28 rows=70 width=4) (actual time=0.885..24.238 rows=12 loops=2)
                           ->  Nested Loop  (cost=178.10..4591.68 rows=1534 width=8) (actual time=0.706..23.260 rows=330 loops=2)
                                 ->  Hash Join  (cost=177.81..4036.66 rows=1534 width=8) (actual time=0.665..22.409 rows=413 loops=2)
                                       Hash Cond: (agent_data_source_configuration."dataSourceId" = "dataSource".id)
                                       ->  Parallel Seq Scan on agent_data_source_configurations agent_data_source_configuration  (cost=0.00..3615.30 rows=92730 width=8) (actual time=0.011..15.857 rows=79556 loops=2)
                                       ->  Hash  (cost=176.15..176.15 rows=133 width=4) (actual time=0.145..0.146 rows=50 loops=2)
                                             Buckets: 1024  Batches: 1  Memory Usage: 10kB
                                             ->  Bitmap Heap Scan on data_sources "dataSource"  (cost=5.65..176.15 rows=133 width=4) (actual time=0.050..0.125 rows=50 loops=2)
                                                   Recheck Cond: (("workspaceId" = 4525) AND ("connectorProvider" IS NULL))
                                                   Heap Blocks: exact=45
                                                   ->  Bitmap Index Scan on data_source_workspace_connector_provider  (cost=0.00..5.61 rows=133 width=0) (actual time=0.035..0.035 rows=57 loops=2)
                                                         Index Cond: (("workspaceId" = 4525) AND ("connectorProvider" IS NULL))
                                 ->  Index Scan using agent_retrieval_configurations_pkey on agent_retrieval_configurations agent_retrieval_configuration  (cost=0.29..0.36 rows=1 width=8) (actual time=0.002..0.002 rows=1 loops=826)
                                       Index Cond: (id = agent_data_source_configuration."retrievalConfigurationId")
                           ->  Index Scan using agent_configurations_pkey on agent_configurations "agent_retrieval_configuration->agent_configuration"  (cost=0.42..2.03 rows=1 width=4) (actual time=0.003..0.003 rows=0 loops=660)
                                 Index Cond: (id = agent_retrieval_configuration."agentConfigurationId")
                                 Filter: ((status)::text = 'active'::text)
                                 Rows Removed by Filter: 1
 Planning Time: 0.911 ms
 Execution Time: 31.101 ms
```

</details>

cc @spolu

**Comment by spolu** [comment]
Can you run it on our workspace id ? 🙏

Cost in the 8000 is definitely a bit expensive. Is there any index we could be missing here?

**Comment by JulesBelveze** [comment]
The explain analyze is actually on our workspace id 😃

I ran it on prodbox so this index is actually missing:
```
CREATE INDEX "agent_configurations_status" ON "agent_configurations" ("status");
```

**Comment by spolu** [comment]
Can you run the explain locally with all indexes set up?

Note: we are not workspace.id = 1;

**Comment by JulesBelveze** [comment]
Yeap the SQL query was generated on my local and then copy pasted on prodbox with the right workspace id 👍🏼 

Here's the explain analyze on my local:
```
 GroupAggregate  (cost=15.94..16.01 rows=1 width=12) (actual time=0.305..0.308 rows=2 loops=1)
   Group Key: "dataSource".id
   ->  Sort  (cost=15.94..15.96 rows=8 width=4) (actual time=0.297..0.299 rows=3 loops=1)
         Sort Key: "dataSource".id
         Sort Method: quicksort  Memory: 25kB
         ->  Hash Join  (cost=1.39..15.82 rows=8 width=4) (actual time=0.237..0.242 rows=3 loops=1)
               Hash Cond: (agent_data_source_configuration."dataSourceId" = "dataSource".id)
               ->  Nested Loop  (cost=0.29..14.58 rows=54 width=4) (actual time=0.138..0.158 rows=12 loops=1)
                     ->  Nested Loop  (cost=0.14..9.31 rows=2 width=4) (actual time=0.110..0.121 rows=6 loops=1)
                           ->  Seq Scan on agent_configurations "agent_retrieval_configuration->agent_configuration"  (cost=0.00..1.15 rows=1 width=4) (actual time=0.069..0.072 rows=5 loops=1)
                                 Filter: ((status)::text = 'active'::text)
                                 Rows Removed by Filter: 7
                           ->  Index Scan using agent_retrieval_configurations_agent_configuration_id on agent_retrieval_configurations agent_retrieval_configuration  (cost=0.14..8.15 rows=1 width=8) (actual time=0.008..0.008 rows=1 loops=5)
                                 Index Cond: ("agentConfigurationId" = "agent_retrieval_configuration->agent_configuration".id)
                     ->  Index Scan using agent_data_source_configurations_retrieval_configuration_id on agent_data_source_configurations agent_data_source_configuration  (cost=0.15..2.60 rows=3 width=8) (actual time=0.005..0.005 rows=2 loops=6)
                           Index Cond: ("retrievalConfigurationId" = agent_retrieval_configuration.id)
               ->  Hash  (cost=1.09..1.09 rows=1 width=4) (actual time=0.062..0.062 rows=3 loops=1)
                     Buckets: 1024  Batches: 1  Memory Usage: 9kB
                     ->  Seq Scan on data_sources "dataSource"  (cost=0.00..1.09 rows=1 width=4) (actual time=0.048..0.049 rows=3 loops=1)
                           Filter: (("connectorProvider" IS NULL) AND ("workspaceId" = 1))
                           Rows Removed by Filter: 4
 Planning Time: 5.661 ms
 Execution Time: 0.551 ms
```

**Review by spolu — APPROVED** [review]
LGTM

**Pull request merged**
