### PR TITLE
[core] Add ff to skip runs details storage

### PR DESCRIPTION
**Pull request by tdraier**
fixes: [#1837](https://github.com/dust-tt/tasks/issues/1837)

## Description

This adds a feature flag that will prevent storage of data in block execution logs.
Note that the feature flag is based on the dust app workspace, so won't be usable for apps in dust_apps used by conversation agents . An additional parameter in the api can be added if needed.

## Risk

none

## Deploy Plan

deploy core
deploy front

### CODE REVIEW

**Review by fontanierh — APPROVED** [review]
code LGTM and no blocker given it's FF-gated, but this breaks the async run API right ? You must always call the API with `blocking=true` ?

**Comment by tdraier** [comment]
> code LGTM and no blocker given it's FF-gated, but this breaks the async run API right ? You must always call the API with `blocking=true` ?

I did not mean to break non blocking api ? Actually I tested locally on dust-apps workspace and it works ok with streaming ?

**Comment by fontanierh** [comment]
Ah yes with streaming indeed, what I meant is you cannot trigger the run and come back later to check the results. But I guess that is expected 👍

**Comment by tdraier** [comment]
> Ah yes with streaming indeed, what I meant is you cannot trigger the run and come back later to check the results. But I guess that is expected 👍 

Yes ofc results are not stored so I assume this is expected if you enable this

**Pull request merged**
