### PR TITLE
🔧 TS/ESLINT config

### PR DESCRIPTION
**Pull request by gmpetrov**
Setup the project for Typescript + Eslint

### CODE REVIEW

**Comment by spolu** [comment]
LGTM

**Comment by spolu** [comment]
Ready to be merged?

**Comment by spolu** [comment]
BTW can you merge yourself when it’s reviewed?

**Comment by spolu** [comment]
I presume no, happy to give you write rights btw

**Review by spolu — APPROVED** [review]

**Comment by gmpetrov** [comment]
Ready to merge!

I can't do it myself i think

**Pull request merged**
