### PR TITLE
Fix: allow admins to reinvite revoked users

### PR DESCRIPTION
**Pull request by philipperolet**
Also prevents inviting a user already in the workspace 
Related [task](https://github.com/dust-tt/tasks/issues/226)

### Notes
- At the time, no email is sent to inform the user that they've been reintegrated to the workspace (shout out if you think we need one)
- Animation of the modal popup: not done, should be done properly using Transition appear=true => sparkle change, for a following PR
- Edge cases that can be safely ignored because very edgy with no impact
  - if an admin is on the page, and a user joins via other means while the admin has not yet send the invitation, the user will receive an email => can be safely ignored
  - if 2 admins are on the page, and one revokes a user, the other will have to reload if needing to invite them again

image

### CODE REVIEW

**Review by spolu — APPROVED** [review]
LGTM

I presume this will be weird when the email invite differs from the email used by the user:
- Invite user by email A
- User joins with email B
- User gets revoked
- Admin wants to re-instate, only way to do it is email B right?

What happens if I resend an invitation to email A in that case?

**Comment by philipperolet** [comment]
You're correct in this case it will be weird. If admin resends an invite to email A instead of B, they will receive an invite link. 
- If they join with email A this time => they will be able to join but won't have their conversation history
- if they join with email B => it will fail saying the user has been revoked

**Comment by philipperolet** [comment]
I will merge & deploy so all the other cases are handled properly which is the priority. @gabhubert if you have remarks on behaviour and copy, happy to add them in a follow-up PR

**Comment by philipperolet** [comment]
Regarding the case you mentioned @spolu , I would say it's fine to wait for it to happen and fix then since my intuition is it won't be a frequent occurence--but would have no problem handling it earlier should you beleive otherwise

**Comment by gabhubert** [comment]
Thanks @pr! 

For copy: (not I'm using $member but I know we currently use "user" in front, we'll have to move it all later)

"$email is a revoked $member of the workspace. Reinstating as $member of the workspace them will also immediately reinstate their conversation history on Dust."

**Pull request merged**
