### PR TITLE
[Meru] Split Assistant builder in 3 screens

### LINKED ISSUE #3776: [Meru - AB] Layout - Split the screen in 3 distinct parts (Instructions, Actions, Naming)
Details on what to do in the **[Figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4900-40669&mode=design&t=6tNvt0C7wUTsOHc4-4)** (also, see how it works in the [Prototype](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?page-id=3366%3A31345&type=design&node-id=4900-40669&viewport=1173%2C2546%2C0.27&t=lV2M2VcNHLWO3Bpe-1&scaling=min-zoom&starting-point-node-id=4900%3A40669) + context & discussion in the [making issue](https://github.com/dust-tt/decisions/issues/164))

- Preview button out of scope; to be done in issue #3778 . In the meantime, preserve the "Try" button from former AssistantBuilder
- Tab should use the new "stepper" variant
- Tab navigation should not be part of history (router.back should take us outside assistant builder)

### PR DESCRIPTION
**Pull request by philipperolet**
## Description
Fixes #3776
- Each screen (instructions, actions, naming) keeps the same layout as before
- The "Delete assistant" button is removed (useless since available more straightforwardly in menu)
image
image
image

## Risk
Only layout change. Available to test on [front edge](https://front-edge.dust.tt)

### TBD: Ship VS wait full-finish
The PR splits the previous builder in 3 screens but the screens are the same as their previous version in builder (as can be seen on [front edge](https://front-edge.dust.tt))

IMHO, although not perfect, this is an improvement from previous AB and can be shipped (also eases transition for users). I understand this opinion is debatable, so pinging you.

If there is a strong argument to not ship, and wait until the 3 screens are fully finished as per figma => we can still work, by using this branch as base branch for Meru. 

This will have an efficiency impact though, the overall ship risk being slower and/or more issue prone--since we build on something not shipped yet while the main codebase still progresses.

### CODE REVIEW

**Comment by philipperolet** [comment]
@Duncid @gabhubert @spolu

Meru deployment - cf **Deploy** section above. My opinion is that shipping would be an improvement over the existant. But if the consensus is that it would be a regression, perfectly fine by me to work on a separate branch until deemed good enough.

**Comment by Duncid** [comment]
Hey @philipperolet !
Thank you for the PR.

There is a little bit of love to bring to spacing between titles and blocks:
image

And to copy (not following https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=3366%3A31345&mode=design&t=wnTu0BLhoqlNaNXH-1)

**Comment by spolu** [comment]
@Duncid this is just the initial layout change we will rapidly iterate on wording + layout :+1: 

@philipperolet the try / next overlapping each other is a bit disatisfying but we will iterate on it rapidly so :+1:

**Review by spolu — APPROVED** [review]

**Comment by philipperolet** [comment]
> Hey @philipperolet ! Thank you for the PR.
> 
> There is a little bit of love to bring to spacing between titles and blocks: image
> 
> And to copy (not following https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=3366%3A31345&mode=design&t=wnTu0BLhoqlNaNXH-1)

Thanks for the reply;  Did you get a chance to read the PR description & in particular the deploy section I've pinged you on? I think this explains why spacing & copy does not fit

**Comment by philipperolet** [comment]
As @spolu said we'll quickly iterate and make other screens fit. @spolu I understand you are in favor of shipping

**Comment by spolu** [comment]
I am in favor of shipping

**Pull request merged**
