### PR TITLE
Agent leaderboard

### PR DESCRIPTION
**Pull request by lasryaric**
New Agents leaderboard view.
Not using any caching for now, but just sending a bunch of queries to our under-used Redis instance, which should work for a good amount of time.

When this becomes a bottleneck, we can add caching or think about a faster version.

Screenshot 2023-12-22 at 16 27 49

### CODE REVIEW

**Review by spolu — COMMENTED** [review]
Let's do a `withStats` on the get agent configurations endpoint that merge the stats if set to true and use that from the gallery?

1 code path. Less code?

**Review by spolu — CHANGES_REQUESTED** [review]
As per IRL:
- we likely want to have a test column in conversations to mark these conversations as such and not display them
- We don't want to start a chat directly and likely want to pass an "additionalAgentConfigurations[]" to the InputBar

**Comment by lasryaric** [comment]
> As per IRL:
> 
> * we likely want to have a test column in conversations to mark these conversations as such and not display them
> * We don't want to start a chat directly and likely want to pass an "additionalAgentConfigurations[]" to the InputBar

wrong PR

**Comment by spolu** [comment]
Oopsy cc @philipperolet

**Comment by philipperolet** [comment]
got it!

**Comment by lasryaric** [comment]
approved by spolu on Slack.

**Comment by spolu** [comment]
👍

**Pull request merged**
