### PR TITLE
Adding an index on AgentGenerationConfiguration.agentConfigurationId

### PR DESCRIPTION
**Pull request by lasryaric**
## Description

Adding an index on AgentGenerationConfiguration.agentConfigurationId to speed up [this](https://console.cloud.google.com/sql/instances/dust-api-db/insights;database=dust-front;duration=PT1H;trace=80c7e236c79f7020ca0118634a7585de;span=de2e9405dfcb2f00;query_hash=13060445737342582110;sort_by=TOTAL_EXEC_TIME/executed?project=or1g1n-186209) query.

## Deploy Plan
- Deploy front and prodbox
- Connect to prod box
- `front> ./admin/init_db.sh`

### CODE REVIEW

**Review by fontanierh — APPROVED** [review]
I thought Sequelize was adding indexes automatically for all foreign keys... Apparently not. Should we add this for every FK ?

**Comment by lasryaric** [comment]
>I thought Sequelize was adding indexes automatically for all foreign keys... Apparently not. Should we add this for every FK ?

I would not do that since adding indexes adds cost to our write and  increase the memory footprint of the DB.
We need to be more careful when designing DB schema from now on (given the size of our DB) and monitoring slow queries (go/slow-queries) on a regular basis is a good way to address that problem in my opinion.

**Comment by lasryaric** [comment]
This would need to be merged at night to avoid a downtime since the table has ~100k entries.

**Comment by fontanierh** [comment]
> This would need to be merged at night to avoid a downtime since the table has ~100k entries.

Should we write a manual migration to add the index concurrently instead ? We have customers in the US so there is no "night" per se

**Comment by lasryaric** [comment]
@fontanierh I don't know where my brain was, Sequelize support the concurrently option. Adding it right now!

**Comment by fontanierh** [comment]
Had no idea @lasryaric

**Comment by lasryaric** [comment]
> Had no idea @lasryaric

@fontanierh done, you can look at the code to check how it works, very simple.

**Pull request merged**
