### PR TITLE
Process Action: Rendering of conversation

### PR DESCRIPTION
**Pull request by spolu**
## Description

- Add missing code for rendering of process action in conversations
- Align interface to RetrievalAction

## Risk

N/A (there is no ProcessAction in production yet)
There is no DB migration here

## Deploy Plan

- No DB migration required (just moving code)
- deploy `front`

### CODE REVIEW

**Comment by spolu** [comment]
Note: we will have to re-order lib/db.ts once we're done with all these inversions

**Comment by spolu** [comment]
PMRR

**Review by lasryaric — COMMENTED** [review]
Perfect! I am taking care of the last one (table query actions) :)

**Comment by spolu** [comment]
\o/

**Pull request merged**
