### PR TITLE
feat(historicize memberships): data model + backfill script

### PR DESCRIPTION
**Pull request by fontanierh**
## Description

https://github.com/dust-tt/tasks/issues/548

This is step 1/n: I am adding the new columns, making sure they are filled-in from business logic when creating new memberships or revoking them, and adding a migration script to backfill the values on old objects.

Next step: start relying on `endDate` instead of `role="revoked"`, remove "revoked" role from DB (will assume "revoked" people were users)

## Risk

Not much here, besides the schema migration (functionally everything is the same)

## Deploy Plan

- deploy prodbox, migrate schema (initdb)
- deploy `front`
- execute migration script

### CODE REVIEW

**Review by spolu — COMMENTED** [review]
Authentication update is missing no?

We likely need in index on endAt to efficiently find null ones?

**Comment by fontanierh** [comment]
> Authentication update is missing no?

As per OP there's no functional changes here

**Review by philipperolet — APPROVED** [review]

**Comment by fontanierh** [comment]
added index @spolu

**Comment by spolu** [comment]
ack I see

**Pull request merged**
