### PR TITLE
clean: migrate lib/datasets to TS and add tests

### PR DESCRIPTION
**Pull request by fontanierh**
- migrate the `front/lib/datasets.js` file to Typescript
- remove the `parse` param, which is unused in the codebase and is broken in the original `checkDatasetData` implementation (`rawData` was referenced but not defined anywhere)
- update code where `checkDatasetData` is called
- add `jest` for tests, and add a few tests for `checkDatasetData`

### CODE REVIEW

**Comment by fontanierh** [comment]
cc @gmpetrov as you started migrating `front/lib` to TS

**Review by spolu — COMMENTED** [review]
LGTM

Thanks for the clean-up of the unused `parse=true` logic

**Review by spolu — DISMISSED** [review]

**Comment by spolu** [comment]
@fontanierh You can merge right?

**Review by spolu — APPROVED** [review]
LGTM

**Comment by fontanierh** [comment]
I don’t think I have merge rights @spolu

**Comment by spolu** [comment]
You have once PRs are reviewed 👍(write permissions)

**Pull request merged**
