### PR TITLE
Fix handling of CSV as pages in Notion

### PR DESCRIPTION
**Pull request by spolu**
## Description

Fixes: https://github.com/dust-tt/tasks/issues/1290

- Fixes the rendering of the section when inserting a database as page in Notion
- Uses the non sanitized header when doing so to prevent replacing accents or other special characters in the document format.

Will test locally before merging:
- [ ] use the small db I created to reproduce and sync it locally
- [ ] check the content of the document locally

## Risk

Low after local testing

## Deploy Plan

- deploy `connectors`

### CODE REVIEW

**Comment by spolu** [comment]
tested locally:

```
Testytest
Tags,Sétup,Name
Bar,Fo,Férie
Bar,Yù,A
Foo,Hey,A
```

looking good

**Comment by spolu** [comment]
The csv may be invalid (headers might have commas, etc...) but since it's the document format I think we're good

**Review by fontanierh — APPROVED** [review]
LGTM

**Comment by Fraggle** [comment]
Excellent, the customer who reported the bug was asking about progress on that one :)

**Comment by Fraggle** [comment]
@spolu thanks for fixing. However, some existing tables are broken and won't be fixed until they change, right ? Do you see a way to identify and re-import theses specifically ?

**Pull request merged**
