### PR TITLE
Retrieval action shows warning on incomplete exhaustive retrieval

### PR DESCRIPTION
**Pull request by philipperolet**
From issue #1865
Exhaustive retrieval with no warning
Screenshot from 2023-10-06 10-44-26
Exh retrieval with warning
Screenshot from 2023-10-06 10-38-23

### CODE REVIEW

**Comment by philipperolet** [comment]
Note: the "Continue" button is for a follow-up PR, as well as handling the case in which "continue" is not relevant because TMI

**Review by spolu — APPROVED** [review]
Looks good.

Screenshot?

**Comment by spolu** [comment]
Ah nvm the screenshot is alraedy here!

**Comment by spolu** [comment]
LGTM :+1:

**Comment by philipperolet** [comment]
As discussed IRL with @gabhubert , merge to be done monday morning

**Pull request merged**
