### PR TITLE
Improve the Dataset View

### PR DESCRIPTION
**Pull request by romainhuet**
This pull request makes a few changes to the dataset view:

* Add a new “Schema” section at the top to define properties and types for the dataset separately from data entries
* Guess the types of properties automatically when opening a dataset or uploading a JSONL file using the first entry
* Validate types when editing with visual feedback to make sure the dataset is valid before saving it
* Provide a code editor for JSON properties to improve autocompletion and syntax highlighting when editing objects
* Add hints/instructions to edit the schema and data when the dataaset isn’t in read-only mode
* Add a “New Entry” button at the bottom left to make it easier to append new entries

Dust Dataset View

It also fixes a small bug on the Runs page to avoid writing “Showing runs 1-0 of 0.”

### CODE REVIEW

**Comment by spolu** [comment]
woot! Will give it a spin and merge ASAP!

**Comment by spolu** [comment]
This is awesome!

Need to dig a tiny bit deeper to find the actual fix but right now when saving a dataset with some JSON objects they get saved as strings (if I then run the app on that saved dataset the output for JSON field is outputed as a string, same when downloading as JSONL, JSON fields are rendered as string in the JSONL)

Hope that makes sense!

**Comment by spolu** [comment]
Other remark, but no need to fix this one to merge. If setting type as string, inputing a number errors. Probably a simple priority issue.

**Comment by romainhuet** [comment]
Thank you @spolu! Good catch on the exported types, it should be fixed now!

As for your other remark, I agree! I’ve been thinking the same thing. Ultimately, we should likely treat `number` and `boolean` as a subset of `string` and presented / validated as such (not only with their `typeof` result).

**Comment by spolu** [comment]
@romainhuet we can punt that to later no problem :+1: 

Last small issue. Going to a dataset and leaving without touching anything triggers the warning. I thinnnk it's a simple matter of having a different useEffect for the new initial setDatasetTypes?

**Pull request merged**
