### PR TITLE
enh: assistants list

### PR DESCRIPTION
**Pull request by fontanierh**

### CODE REVIEW

**Review by spolu — DISMISSED** [review]
ContextItem is a surprising name I’m not sure I get the exact purpose ooc?

**Comment by fontanierh** [comment]
It's not from me, but from storybook it's essentially a list item

**Comment by spolu** [comment]
Yep let's see what was the naming motivation from @Duncid

**Review by spolu — APPROVED** [review]

**Comment by Duncid** [comment]
I actually spent a bit of time thinking of the name.
I'm not fully satisfied.

I call it context because it can provide more context on the item than a simple normal item (an image, a description, an action).

I also thought of:
- ComplexItem
- RichItem

**Pull request merged**
