### PR TITLE
fix type error

### PR DESCRIPTION
**Pull request by fontanierh**

### CODE REVIEW

**Review by flvndvd — COMMENTED** [review]
Given that we have some proper tooling to achieve this today, should we delete this file?

**Comment by fontanierh** [comment]
@flvndvd I'm not opposed, but @spolu wants to keep them for posterity

**Comment by flvndvd** [comment]
> @flvndvd I'm not opposed, but @spolu wants to keep them for posterity

While having a history is valuable in 99% of the situations, this one might be an exception. We invested in our tooling to make this regular task easier and more accessible. We definitely want to avoid promoting the practice of writing a new migration each time a model requires to be bumped 🙃 .

**Comment by fontanierh** [comment]
Top of the migration says to not use this and instead use the script.
But agree this one should likely be deleted

**Comment by spolu** [comment]
Fine to delete. The idea is to keep things around but if there is reason to remove it's fine to remove :+1:

**Pull request merged**
