### PR TITLE
Gdrive: Mark it as successfully sync at creation time.

### PR DESCRIPTION
**Pull request by lasryaric**
## Description

Eng runner card: https://github.com/dust-tt/tasks/issues/701

When connecting a Google Drive connector, the connector is not never marked as "successfully synced" if the user never select some folders to sync, because the full sync workflow is never kick started.

While this is a rare event, this is a possible user flow, so this PR marks the connector as "successfully synced" right after creation, which will be overridden when the user selects some folders to synchronize.

That way, we avoid showing an infinite "syncing" chip on the UI if the user ends up not selecting folders to synchronize.

# Before
Screenshot 2024-04-23 at 15 41 42

# After
Screenshot 2024-04-23 at 15 41 20

### CODE REVIEW

**Review by philipperolet — APPROVED** [review]
LGTM, assuming you double-checked that users who did select folders will not wrongfully see a "synchronized" chip for a while

**Comment by lasryaric** [comment]
>LGTM, assuming you double-checked that users who did select folders will not wrongfully see a "synchronized" chip for a while

It will show as "synchronized" for a little bit before going back into a "synchronizing..." state again.

@philipperolet if you think this is not acceptable, and I can agree with that, I will just close this PR as this is not high priority enough.
I checked in the database, only 3 Gdrive connectors do not have any folder selected.

**Comment by philipperolet** [comment]
> > LGTM, assuming you double-checked that users who did select folders will not wrongfully see a "synchronized" chip for a while
> 
> It will show as "synchronized" for a little bit before going back into a "synchronizing..." state again.
> 
> @philipperolet if you think this is not acceptable, and I can agree with that, I will just close this PR as this is not high priority enough. I checked in the database, only 3 Gdrive connectors do not have any folder selected.

Hey! For me it all depends on the "little bit". If it can lead to situations in which for e.g. 15mns or more a user that selected folders will see "synchronized" whereas the sync hasn't happened, then I'd rather close as you mentioned

But if it's never more than a few seconds or a minute or so, then for me it's fine you can merge :+1:

**Comment by lasryaric** [comment]
@philipperolet ok so the problem today is that the little ship is auto refreshed only if it's been in a `synchronizing` state when the client side got the `ConnectorType`. I will change it to have it auto refresh itself if `ConnectorType.updatedAt` is smaller than `X` minutes. That way, it's a nearly perfect world.

Also, I have seen multiple occasions where the chip should have been auto refreshing and was not.

**Comment by lasryaric** [comment]
@philipperolet I added the refreshing of the connector chip based on the `ConnectorType.updatedAt` field.

Can you take a look? 🙏

**Review by philipperolet — APPROVED** [review]
:+1:

**Pull request merged**
