### PR TITLE
enh: Connected data source management

### LINKED ISSUE #2200: [Doom] Management of Connected Data sources
From: https://github.com/dust-tt/decisions/issues/105

See [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=2389%3A13138&mode=design&t=jNPh15R04TKGjgcX-1):

image

Changes:
- Clearly state that the display is the display of the syncronized data and clarify CTAs

### PR DESCRIPTION
**Pull request by spolu**
Fixes: https://github.com/dust-tt/dust/issues/2200

Screenshot from 2023-11-03 12-56-46
Screenshot from 2023-11-03 12-56-52
Screenshot from 2023-11-03 12-57-04

### CODE REVIEW

**Review by philipperolet — APPROVED** [review]
LGTM!

**Comment by philipperolet** [comment]
Hmm apparently the hydration error is still here; not related to this PR per se and not blocking the merge though

**Comment by philipperolet** [comment]
AFAICT the use of Page.P with div is the root cause (no div inside a P) => the fix would be to change Page.P accordingly in sparkle, taking

**Comment by philipperolet** [comment]
Who uses <p> anyways?

**Comment by spolu** [comment]
That Page.P does :) Thanks for taking!

**Pull request merged**
