### PR TITLE
enh(builder multi actions): use input fields as per design

### PR DESCRIPTION
**Pull request by fontanierh**
## Description

https://github.com/dust-tt/dust/issues/5007
https://github.com/dust-tt/decisions/issues/213

Screenshot 2024-05-21 at 17 46 52

Screenshot 2024-05-21 at 17 47 00

Should now be more or less compliant w/ the design

## Risk

multi-actions only so should be fine

### CODE REVIEW

**Comment by spolu** [comment]
I created a multi action assistant based on Dust apps during a demo, is that expected that we don't pull the dust app description and name automatically?

**Comment by fontanierh** [comment]
But not sure we should override something you wrote if you change the app though @spolu

**Comment by spolu** [comment]
Well I def def def want to have it pulled here as I pick the app. Maybe we do it only if the field is empty and don't put a default in?

**Review by spolu — APPROVED** [review]

**Review by PopDaph — APPROVED** [review]

**Comment by fontanierh** [comment]
> Well I def def def want to have it pulled here as I pick the app. Maybe we do it only if the field is empty and don't put a default in?

👍

**Pull request merged**
