### PR TITLE
Front: Display Intercom connections as coming soon

### PR DESCRIPTION
**Pull request by PopDaph**
Looks like a lot of code but no complex logic, this PR is only about adding to the Plan db and type a "isIntercomAllowed". 
UI changes for the members are on the Connection pages, where we display this new button. 

### Deployment
Requires a db migration: `./admin/init_db.sh` to add the new field `isManagedIntercomAllowed` to `Plan`.
Requires updating the Prod pro plan afterward to set intercom allowed to true.

### UI Change
Screenshot 2023-11-16 at 15 50 00

### CODE REVIEW

**Comment by PopDaph** [comment]
This PR is the best way to motivate myself to quickly ship this new connector 😅

**Review by fontanierh — DISMISSED** [review]
LGTM

**Comment by PopDaph** [comment]
Added a commit to handle @gabhubert's feedback, see here: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1700149755784309?thread_ts=1700147434.773509&cid=C050A0S2Z7F

**Comment by spolu** [comment]
:fire:

**Review by spolu — APPROVED** [review]

**Pull request merged**
