### PR TITLE
Set custom search attribute 'connectorId' for temporal workflows

### PR DESCRIPTION
**Pull request by philipperolet**
The PR below will add a connector id search attribute for our workflows. As explained by [temporal](https://docs.temporal.io/dev-guide/typescript/observability#visibility) this allows to programatically retrieve all workflows by their connector id (+ other filters as an SQL-like where clause)
The first use case is killing running gdrive workflows when we delete the connector.

### CODE REVIEW

**Review by spolu — APPROVED** [review]
Oh wow!

**Review by lasryaric — CHANGES_REQUESTED** [review]
@philipperolet I think you might need to add it to child workflow in workflows.ts files.

**Comment by lasryaric** [comment]
@philipperolet for reference:
```

  await executeChild(slackGarbageCollectorWorkflow, {
    workflowId: slackGarbageCollectorWorkflowId(connectorId),
    args: [connectorId],
    memo: workflowInfo().memo,
    searchAttributes: workflowInfo().searchAttributes,
  });

```

**Comment by philipperolet** [comment]
Ack, thanks :pray: Will update then merge

**Comment by philipperolet** [comment]
cc @PopDaph @fontanierh @flvndvd FYI, argument to add when starting a workflow

**Comment by philipperolet** [comment]
- child workflows updated
- version numbers bumped
- no need to restart workflows since they will automatically pick up the new code when they're continuedasnew

**Pull request merged**
