### PR TITLE
URL revamp DUST_PROD_API

### PR DESCRIPTION
**Pull request by lasryaric**
DUST_PROD_API  part of the URLs revamp from this [design doc](https://www.notion.so/dust-tt/Engineering-e0f834b5be5a43569baaf76e9c41adf2?p=8e1aab69fdb84809b8be4fc9f75e719e&pm=s).

Deployment:
```
kubectl patch secret front-secrets -p '{"stringData":{"DUST_PROD_API":"http://front-service"}}'
```

Deploy front via github action

### CODE REVIEW

**Review by spolu — COMMENTED** [review]
We probably need to update `front/lib/auth.ts` as well no?

**Comment by lasryaric** [comment]
>We probably need to update front/lib/auth.ts as well no? 

@spolu I think the URL in `front/lib/auth` should actually be replaced by `DUST_CLIENT_FACING_URL`.
And it should even maybe just look at the request.headers['host'].

**Comment by spolu** [comment]
I don't think that's right since `front/lib/auth`'s `DUST_API` is used for `prodAPICredentialsForOwner` which is used with DustAPI everywhere in `front` ?

**Comment by spolu** [comment]
the `DUST_API` of `front/lib/auth` is set to `https://dust.tt` in development unless specifically set to localhost for very particular reasons

**Comment by lasryaric** [comment]
Ok I miss read its usage. I am glad we are doing this revamp. I will add it to `front/lib/auth` 🙏

**Review by spolu — APPROVED** [review]

**Pull request merged**
