### PR TITLE
feat: add links to dust app logs in poke

### PR DESCRIPTION
**Pull request by fontanierh**
## Description

fixes https://github.com/dust-tt/tasks/issues/412

Hide whitespace changes for extra fun.

Screenshot 2024-02-09 at 09 54 37

### CODE REVIEW

**Comment by lasryaric** [comment]
@fontanierh can you add a screenshot please? I am having a hard time getting it.

**Review by lasryaric — APPROVED** [review]
LGTM

**Comment by fontanierh** [comment]
> @fontanierh can you add a screenshot please? I am having a hard time getting it.

@lasryaric  I can recommend a great optometrist if needed :)

**Comment by spolu** [comment]
We don't have access to other workspaces logs do we? or did we implement super user support there?

**Comment by fontanierh** [comment]
> We don't have access to other workspaces logs do we? or did we implement super user support there?

As per IRL, we do as super users

**Pull request merged**
