### PR TITLE
[Infra] Log activity failures due to startToCloseTimeout

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Fixes https://github.com/dust-tt/tasks/issues/747

We log activity failures when the activity reports an error. Activities that exceed their startToClose timeout may not report an error and keep running, while temporal marks them as failed and retries them. We don't get any log and are not warned.

This can cause various issues that are hard to debug (because no logs), see e.g. https://github.com/dust-tt/tasks/issues/734

This PR makes it so we log when an activity exceeds its startoclose timeout exactly the same way as for other failures

Risk
---
N/A

Deploy plan
---
Connectors

### CODE REVIEW

**Comment by philipperolet** [comment]
Closed PR #5045 which had another approach

**Comment by lasryaric** [comment]
Asked on the Temporal Slack channel how to monitor startToCLose timeout activity errors:
https://temporalio.slack.com/archives/C01DKSMU94L/p1715699537175389

**Comment by philipperolet** [comment]
Removed the promise.race :racehorse: :smile:

**Review by fontanierh — APPROVED** [review]
I was writing a long comment and before I finished you updated to something much less controversial :p 

This looks fine 👍

**Comment by philipperolet** [comment]
With the changes discussed (no more race, simple setTimeout), the PR becomes less risky => one approval is enough. Merging

**Comment by lasryaric** [comment]
Please update the error field to reflect the `startToCloseTimeout` error accordingly. 🙏

**Pull request merged**
