### PR TITLE
Make the Slack Bot talk to the local front app

### PR DESCRIPTION
**Pull request by lasryaric**

### CODE REVIEW

**Review by PopDaph — APPROVED** [review]
Thanks @lasryaric!

**Review by spolu — COMMENTED** [review]
Can we also update `front`'s `dust_api.ts` as well as `auth.ts` so that we have consistency on naming?

**Comment by spolu** [comment]
What's the rationale for changing the name and using two different names?

**Review by spolu — CHANGES_REQUESTED** [review]
As per slack discussion I think this PR requires a bit more documentation :pray:

**Comment by spolu** [comment]
Can we close given that it's staled vs the design?

**Comment by lasryaric** [comment]
Yes.

**Pull request closed without merging**
