### PR TITLE
🧹 Use aliases instead of relative imports

### LINKED ISSUE #167: front: use module path aliases
W'd be great to switch from relative imports to aliases https://nextjs.org/docs/advanced-features/module-path-aliases

```js
import AppLayout from "../../../components/AppLayout";

import AppLayout from "@app/components/AppLayout";
```

What do you think?

### PR DESCRIPTION
**Pull request by gmpetrov**
Lots of updated files! Have fun @spolu 😛

closes #167

### CODE REVIEW

**Comment by spolu** [comment]
Hahah! Will review. Bullish on this 👍

**Comment by spolu** [comment]
By review I mean testing each page separately 😅

**Review by spolu — APPROVED** [review]
LGTM

**Comment by fontanierh** [comment]
@gmpetrov  Do you manage to resolve paths from VSCode with path aliases ? I would have expected it to pick up the `tsconfig.json` but apparently it does not (things like cmd+click or go to definition don't work).

Is there a specific setting to turn on ?

**Comment by gmpetrov** [comment]
@fontanierh Yes, it works well on my side with vscode. I'm able to go to def etc...
Do you load dust's root folder in vsode ? or just front?

**Pull request merged**
