### PR TITLE
Allow null score for retrieved documents (redo)

### PR DESCRIPTION
**Pull request by philipperolet**
Fix of PR #1966 that was reverted by #1970

### CODE REVIEW

**Comment by philipperolet** [comment]
There was a missing "return" in the sort by score statement. It didn't show when I tested because I was locally set to do query=none retrievals---and the last conversations in my history were such instances too
:bow: for the mistake

**Comment by spolu** [comment]
That does not explain that some retrievals worked? They should have all failed no?

**Review by spolu — APPROVED** [review]

**Comment by philipperolet** [comment]
The return was there when scores were both null; it was omitted when scores were both there => as such it didn't fail for query=none retrievals

**Comment by spolu** [comment]
Right but you mentioned "some retrieval worked" during the incident I believe. Do you confirm that none worked at all?

**Comment by philipperolet** [comment]
yes. As I saw multiple conversations working on my end, I worte this as part of the investigation process I was on. Retrospectively, in production, all retrievals failed since there are no retrieval with query = none

**Pull request merged**
