### PR TITLE
enh(zendesk-cli) - allow passing a custom query to `count-tickets`

### PR DESCRIPTION
**Pull request by aubin-tchoi**
## Description

- This PR adds the possibility to customize the query used when counting the tickets in the admin CLI.

## Risk

- Very low, only affects the admin cli.

## Deploy Plan

- Deploy connectors.

### CODE REVIEW

**Review by Fraggle — APPROVED** [review]
Investigating the thing you told me yesterday ?

**Comment by aubin-tchoi** [comment]
yep :p

**Comment by aubin-tchoi** [comment]
dumping some logs here:
```root@connectors-deployment-d8c75b779-5fncx:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501 --brandId 17320677699345 --query "status:solved updated>6months"
{"level":"info","time":1733910468929,"pid":441,"hostname":"connectors-deployment-d8c75b779-5fncx","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"status:solved updated>6months"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":14675,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 14675
}
Done
root@connectors-deployment-d8c75b779-5fncx:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501 --brandId 17320677699345 --query "status:closed updated>6months"
{"level":"info","time":1733910499986,"pid":477,"hostname":"connectors-deployment-d8c75b779-5fncx","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"status:closed updated>6months"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":941043,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 941043
}
Done```

**Comment by aubin-tchoi** [comment]
dumping some more logs
```
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "status:solved updated>2024-06-11"
{"level":"info","time":1733956077239,"pid":132,"hostname":"connectors-deployment-f5c984f7f-zp9v2","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"status:solved updated>2024-06-11"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":14197,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 14197
}
Done
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "status:solved updated>2024-06-11 updated<2024-17-11"
^C
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "status:solved updated>2024-06-11 updated<2024-07-11"
{"level":"info","time":1733956110711,"pid":199,"hostname":"connectors-deployment-f5c984f7f-zp9v2","dd":{"service":"connectors","version":"0.1.0","env":"prod"},"elapsedTime":101,"callStack":"Error\n    at Sequelize.afterPoolAcquire (/app/src/resources/storage/index.ts:53:26)\n    at Sequelize.runHooks (/app/node_modules/sequelize/src/hooks.js:131:18)\n    at ConnectionManager.getConnection (/app/node_modules/sequelize/src/dialects/abstract/connection-manager.js:291:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/app/node_modules/sequelize/src/sequelize.js:638:26)\n    at PostgresQueryInterface.select (/app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1001:12)\n    at Function.findAll (/app/node_modules/sequelize/src/model.js:1824:21)\n    at Function.findOne (/app/node_modules/sequelize/src/model.js:1998:12)\n    at Function.findByPk (/app/node_modules/sequelize/src/model.js:1955:12)\n    at Function.fetchById (/app/src/resources/base_resource.ts:40:18)","msg":"Long sequelize connection acquisition detected"}
{"level":"info","time":1733956111345,"pid":199,"hostname":"connectors-deployment-f5c984f7f-zp9v2","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"status:solved updated>2024-06-11 updated<2024-07-11"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":0,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 0
}
Done
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "status:solved updated>2024-08-11 updated<2024-09-11"
{"level":"info","time":1733956142122,"pid":235,"hostname":"connectors-deployment-f5c984f7f-zp9v2","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"status:solved updated>2024-08-11 updated<2024-09-11"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":0,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 0
}
Done
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "status:solved updated>2024-10-11 updated<2024-11-11"
{"level":"info","time":1733956160545,"pid":271,"hostname":"connectors-deployment-f5c984f7f-zp9v2","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"status:solved updated>2024-10-11 updated<2024-11-11"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":0,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 0
}
Done
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "status:solved updated>2024-11-11 updated<2024-12-11"
{"level":"info","time":1733956176808,"pid":307,"hostname":"connectors-deployment-f5c984f7f-zp9v2","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"status:solved updated>2024-11-11 updated<2024-12-11"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":6365,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 6365
}
Done
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "status:closed updated>2024-07-11 updated<2024-08-11"
{"level":"info","time":1733956205988,"pid":343,"hostname":"connectors-deployment-f5c984f7f-zp9v2","dd":{"service":"connectors","version":"0.1.0","env":"prod"},"elapsedTime":122,"callStack":"Error\n    at Sequelize.afterPoolAcquire (/app/src/resources/storage/index.ts:53:26)\n    at Sequelize.runHooks (/app/node_modules/sequelize/src/hooks.js:131:18)\n    at ConnectionManager.getConnection (/app/node_modules/sequelize/src/dialects/abstract/connection-manager.js:291:28)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at <anonymous> (/app/node_modules/sequelize/src/sequelize.js:638:26)\n    at PostgresQueryInterface.select (/app/node_modules/sequelize/src/dialects/abstract/query-interface.js:1001:12)\n    at Function.findAll (/app/node_modules/sequelize/src/model.js:1824:21)\n    at Function.findOne (/app/node_modules/sequelize/src/model.js:1998:12)\n    at Function.findByPk (/app/node_modules/sequelize/src/model.js:1955:12)\n    at Function.fetchById (/app/src/resources/base_resource.ts:40:18)","msg":"Long sequelize connection acquisition detected"}
{"level":"info","time":1733956206648,"pid":343,"hostname":"connectors-deployment-f5c984f7f-zp9v2","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"status:closed updated>2024-07-11 updated<2024-08-11"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":146033,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 146033
}
Done
```

**Comment by aubin-tchoi** [comment]
```
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "type:ticket status:solved"
{"level":"info","time":1733957387961,"pid":674,"hostname":"connectors-deployment-f5c984f7f-zp9v2","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"type:ticket status:solved"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":14210,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 14210
}
Done
root@connectors-deployment-f5c984f7f-zp9v2:/app# ./admin/cli.sh zendesk count-tickets --connectorId 11501  --brandId 17320677699345 --query "type:ticket status>=solved"
{"level":"info","time":1733957406904,"pid":710,"hostname":"connectors-deployment-f5c984f7f-zp9v2","majorCommand":"zendesk","command":"count-tickets","args":{"connectorId":11501,"brandId":17320677699345,"query":"type:ticket status>=solved"},"dd":{"service":"connectors","version":"0.1.0","env":"prod"},"connectorId":"11501","brandId":17320677699345,"ticketCount":972195,"retentionPeriodDays":180,"msg":"Number of valid tickets found for the brand."}
{
  "ticketCount": 972195
}
Done
```

**Pull request merged**
