### PR TITLE
Retire Docs k8s

### PR DESCRIPTION
**Pull request by albandum**
## Description

Retiring docs from kube

## Deploy Plan

Manually nuke docs pods

### CODE REVIEW

**Review by fontanierh — CHANGES_REQUESTED** [review]
Redlines FTW 🤩 

This won't actually work, we need to remove all references to those yamls in `apply_infra.sh`. Then we'll need to manually delete those resources from kube via kubectl. I can take that last part (or show you how to) if you don't have a kube setup locally 👍

**Comment by albandum** [comment]
> This won't actually work, we need to remove all references to those yamls in `apply_infra.sh`. Then we'll need to manually delete those resources from kube via kubectl. I can take that last part (or show you how to) if you don't have a kube setup locally 👍

Oops, added the apply_infra modifs.
I do have kube setup - dw I'll nuke them after that's all done.

**Review by fontanierh — APPROVED** [review]
✨

**Comment by fontanierh** [comment]
> Manually nuke docs pods

Just to make sure we are aligned -- not actually the pods: the deployment, the service, the managed cert, the configmap. The pods will follow by themselves

**Comment by albandum** [comment]
> > Manually nuke docs pods
> 
> Just to make sure we are aligned -- not actually the pods: the deployment, the service, the managed cert, the configmap. The pods will follow by themselves

Aright, will wait for monday and might ping you if needed

**Pull request merged**
