### PR TITLE
continue typing dust API (2)

### PR DESCRIPTION
**Pull request by fontanierh**

### CODE REVIEW

**Review by spolu — APPROVED** [review]
LGTM

(Did you test each code path locally. In particular just want to make sure that streaming still works through the API. Happy to test it on my machine if you like).

**Review by spolu — APPROVED** [review]
LGTM

(Did you test each code path locally. In particular just want to make sure that streaming still works through the API. Happy to test it on my machine if you like).

**Comment by fontanierh** [comment]
Yes, I tested and everything appears to still work the same

**Comment by fontanierh** [comment]
But a double check from you could be useful !

**Comment by spolu** [comment]
Wilco before deploying 👍

**Pull request merged**
