### PR TITLE
Add partial active index on agent_configurations

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

The query to list all the agent configurations is pretty slow and is being called a numerous number of times.

https://console.cloud.google.com/sql/instances/dust-api-db/insights;database=dust-front;duration=PT1H;trace=90c1cf686c8a62bf976c6140481df681;span=fd05e5b77537c5f5;query_hash=4445849333423358681;sort_by=TOTAL_EXEC_TIME/executed?project=or1g1n-186209

The current existing index `"agent_configurations_workspace_id_status_name" btree ("workspaceId", status, name)` helps but does not allow us to use a index_only query and requires a bitmap heap scan. A quick look at our DB, reveals that active assistants represent only 5% of the rows from the `agent_configurations` table.
Out of 305k rows, only 14385 are active assistants, 210k are drafts and 81k are archive.

We've been discussing for a long time the need to solve the draft situation, until we get there, this PR adds a partial index, that will only focus on active agent configurations, this should make the index very light.

Current explain:
```
dust-front=> EXPLAIN ANALYZE SELECT  "id",  "createdAt",  "updatedAt",  "sId",  "version",  "status",  "scope",  "name",  "description",  "instructions",  "providerId",  "modelId",  "temperature",  "maxStepsPerRun",  "visualizationEnabled",  "pictureUrl",  "groupIds",  "workspaceId",  "authorId",  "templateId" FROM  "agent_configurations" AS "agent_configuration" WHERE  ("agent_configuration"."scope" IN ('workspace', 'published')    OR "agent_configuration"."authorId" = 4425)  AND "agent_configuration"."workspaceId" = 4525  AND "agent_configuration"."status" = 'active'
;
                                                                        QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------------------------
 Bitmap Heap Scan on agent_configurations agent_configuration  (cost=13.04..1723.08 rows=78 width=802) (actual time=1.683..2.973 rows=355 loops=1)
   Recheck Cond: (("workspaceId" = 4525) AND ((status)::text = 'active'::text))
   Filter: (((scope)::text = ANY ('{workspace,published}'::text[])) OR ("authorId" = 4425))
   Rows Removed by Filter: 219
   Heap Blocks: exact=556
   ->  Bitmap Index Scan on agent_configurations_workspace_id_status_name  (cost=0.00..13.02 rows=460 width=0) (actual time=1.566..1.566 rows=608 loops=1)
         Index Cond: (("workspaceId" = 4525) AND ((status)::text = 'active'::text))
 Planning Time: 2.591 ms
 Execution Time: 3.055 ms
(9 rows)
```

## Deploy Plan

- [ ] Run migration
- [ ] Check explain analyze output

### CODE REVIEW

**Review by philipperolet — APPROVED** [review]
Thanks :pray: Just to check did you test it actually improve the query?

Even without the drafts, the index would be 15% of the rows, and will likely get smaller as people update their assistants => IMO the index is good anyways

**Comment by flvndvd** [comment]
> Thanks 🙏 Just to check did you test it actually improve the query?
Hard to test locally, as I don't have enough rows, so everything happens in memory.

**Review by fontanierh — APPROVED** [review]
LGTM

**Comment by flvndvd** [comment]
New explain:
```
 Bitmap Heap Scan on agent_configurations agent_configuration  (cost=22.30..330.49 rows=78 width=802) (actual time=0.098..0.652 rows=355 loops=1)
   Recheck Cond: ((("workspaceId" = 4525) AND ((scope)::text = ANY ('{workspace,published}'::text[])) AND ((status)::text = 'active'::text)) OR (("workspaceId" = 4525) AND ("authorId" = 4425) AND ((status)::
text = 'active'::text)))
   Heap Blocks: exact=335
   ->  BitmapOr  (cost=22.30..22.30 rows=79 width=0) (actual time=0.055..0.056 rows=0 loops=1)
         ->  Bitmap Index Scan on partial_agent_config_active  (cost=0.00..9.35 rows=77 width=0) (actual time=0.048..0.048 rows=345 loops=1)
               Index Cond: (("workspaceId" = 4525) AND ((scope)::text = ANY ('{workspace,published}'::text[])))
         ->  Bitmap Index Scan on partial_agent_config_active  (cost=0.00..12.91 rows=2 width=0) (actual time=0.007..0.007 rows=31 loops=1)
               Index Cond: (("workspaceId" = 4525) AND ("authorId" = 4425))
 Planning Time: 0.217 ms
 Execution Time: 0.703 ms
```

Looks like it performs better, the planning time could probably be improved by removing previous indexes. Will keep monitoring.

**Pull request merged**
