### PR TITLE
fix: box-shadow instead of drop-shadow

### PR DESCRIPTION
**Pull request by fontanierh**
Drop-shadow is clashing with backdrop-blur on firefox...
https://github.com/dust-tt/tasks/issues/242

### CODE REVIEW

**Review by spolu — DISMISSED** [review]
LGTM

This is disgusting. But heh :)

**Comment by fontanierh** [comment]
> This is disgusting. But heh :)

Yes it's horrific.

I did a pass and it seems fine visually, but I wouldn't mind some confirmation from you -- I am not the best at assessing quality of drop shadows @spolu

**Comment by spolu** [comment]
Looking

**Comment by spolu** [comment]
Looks reasonable. The real problem is that we have no good way to prevent the use of box-shadow vs drop-shadow. Which begs the question. Should we only use box-shadow where we have known interactions with backdrop-blur

Basically the modal and the input bar only?

**Comment by fontanierh** [comment]
> Looks reasonable. The real problem is that we have no good way to prevent the use of box-shadow vs drop-shadow. Which begs the question. Should we only use box-shadow where we have known interactions with backdrop-blur

> Basically the modal and the input bar only?

I suppose we _could_ try to write a linter rule, but let's not do that. Indeedit would be reasonable to limit this to input bar and modal 👍 

It's likely to happen again at some point, but hopefully by then mozilla will have fixed their browser


Making the change

**Comment by fontanierh** [comment]
Reverted changes except in modal and input bar @spolu

**Comment by spolu** [comment]
Thanks!

**Pull request merged**
