### PR TITLE
Add log event when Chat session is upserted

### PR DESCRIPTION
**Pull request by PopDaph**
Adding a new log to be able to monitor chat sessions from Datadog. 
Source: [Slack Thread](https://dust4ai.slack.com/archives/C050A0S2Z7F/p1688647377091499)

### CODE REVIEW

**Review by spolu — DISMISSED** [review]
LGTM but session upsert will happen after each user interaction so it's still not really a "new session count"

**Comment by spolu** [comment]
Ah I didn't see the `created` :+1: but does it exist?

**Review by spolu — COMMENTED** [review]
For convenience if `created` we may want to increase a statsDClient counter so that we can graph new chat session?

**Comment by philipperolet** [comment]
:+1: LGTM

**Review by philipperolet — DISMISSED** [review]

**Review by spolu — APPROVED** [review]
LGTM

**Pull request merged**
