### PR TITLE
[Poke] Check notion url from notion page in Poke

### PR DESCRIPTION
**Pull request by philipperolet**
## Description

Fixes https://github.com/dust-tt/tasks/issues/517

Surprisingly took longer than expected; needed a small type refactor too

Screenshot from 2024-03-14 15-13-02

### CODE REVIEW

**Review by spolu — CHANGES_REQUESTED** [review]
Discussed IRL

Let's move on a generic but POKE specific interface / endpoint.

Let's type it  and verify it as much as possible (command: PokeCommand, args {[key: string]: string}) or similar

**Comment by philipperolet** [comment]
:+1: Will make the creation of the poke endpoint in a separate PR, then use it in this one

**Comment by philipperolet** [comment]
New poke endpoint live. This PR updated with correct API call

**Review by fontanierh — APPROVED** [review]
Awesome !

**Pull request merged**
