### PR TITLE
Add fallback assistant suggestions

### LINKED ISSUE #3277: [Nice-to-have] InputBar @mention completion is smarter
As per bottom of the framing [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

----------
Full [figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22251&mode=design&t=Dlhq25QyeMahW2OI-0) (source of truth)

Full [issue](https://github.com/dust-tt/decisions/issues/147#issue-2081773564)

Even clearer specs via the [prototype](https://www.figma.com/proto/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4050-22252&t=PrquaF04miEgyEMq-0&scaling=min-zoom&page-id=4050%3A22251&starting-point-node-id=4050%3A22252&show-proto-sidebar=1)

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

This PR resolves https://github.com/dust-tt/dust/issues/3277.

This PR introduces the concept of fallback suggestions to the assistant suggestions in our input bar. The primary goal is to initially recommend assistants from the user's personal list. If the list yields less than 7 suggestions, it then includes accessible assistants not present on the user’s list. The two sets of suggestions will be sorted respectively. We may revisit this sorting approach in the future.

This enhancement does not impact the speed of suggestions. Initially, as we fetch all suggestions, only those from the user's list will be displayed.

assistantSuggestions
In this GIF, `dusttestflavien` isn't in my list, but is suggested when we have less than 7 suggestions.

### CODE REVIEW

**Review by philipperolet — CHANGES_REQUESTED** [review]
Code looks good, do we intend the loading to be fast with the call to "all"?

I wonder about the user side of things, thus the changes requested, see com below

**Comment by philipperolet** [comment]
Code looks good, do we intend the loading to be fast with the call to "all"?

However I wonder about the user side

As a user, I don't like having a cluttered list of suggestions;
Also, if I removed an assistant from my list, I'll be annoyed to see it pop up when I type (even if it is not selected in the end); the list narrowing down is kind of a visual confirmation that I typed the I wanted right
I feel that this makes the distinction "in my list" / "not in my list" less useful. If we are sure we want to add these suggestions, then as a user I would prefer:
that they only appear if none of my agents match;
that the UI makes it clear (ie. a small title "assistants shared by other users" in the suggestions) so that I know that nothing matches from my list and that what I'm shown is a suggestion that's from outside it
ccing @Duncid to discuss

**Comment by flvndvd** [comment]
> Code looks good, do we intend the loading to be fast with the call to "all"?
> 
> I wonder about the user side of things, thus the changes requested, see com below

As mentioned in the PR description, retrieving "all" the assistants doesn't significantly affect our suggestions because they serve as a fallback. Therefore, this won't worsen today's performances 🙃.

**Comment by philipperolet** [comment]
Ok understood, IMHO the visual separation would make a diff, and solve the pb from the strange effect mentionned by flavien (since it makes the user understand that new suggestions are coming). 

But fine to see how it goes like this and change after

**Pull request merged**
