### PR TITLE
[templates] Add empty string to timeFrameUnit for the rest of the templates

### PR DESCRIPTION
**Pull request by albandum**
## Description

Fix - regular templates could not be saved without a timeframe unit

### CODE REVIEW

**Comment by spolu** [comment]
Wait isn't it the sign that we're passing strings where we whould be passing undefined?

**Comment by albandum** [comment]
> Wait isn't it the sign that we're passing strings where we should be passing undefined?

Seems like it's only on the form itself. It's a react-hook-form thing visibly, but this seems to be blocking even when the action selected is not `process_action` (meaning: even when the timeFrameUnit input is not in the DOM) 🤔 
I've turned it around a bit and for now that's the only solution I came up with, but there may be a way to remove the empty string before the form.onSubmit() ?

**Review by spolu — APPROVED** [review]
SGTM. Let's make sure the schema of non process action are as epexcted after saving with this change but otherwise LGTM

**Comment by albandum** [comment]
> SGTM. Let's make sure the schema of non process action are as epexcted after saving with this change but otherwise LGTM

Yep already checked, we're good

**Pull request merged**
