### PR TITLE
[Infra] Add production check to detect startToClose timeouts

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Fixes https://github.com/dust-tt/tasks/issues/747

StartToClose timeout failures are not logged in datadog and the activity is not terminated by temporal, but temporal retries by starting a new activity with same id. Multiple activity clones running at the same time can cause various issues, such as OOMs (activities pile up)

Risk
---
N/A

Deploy plan
---
Front

### CODE REVIEW

**Review by lasryaric — COMMENTED** [review]
Is there a way to check for the activity attempt number? I think a few startToCLose timeout should be tolerable, no?

**Comment by philipperolet** [comment]
Unfortunately, I think we should go check at the first one.
In general, when you have even just one startToClose timeout, it means you might have 2 same activities running at the same time (because temporal retried while the initial activity was not killed) which can cause unpredictable, hard to debug issues

**Comment by lasryaric** [comment]
@philipperolet it could also be an activity that takes 20 minutes that got killed because of a deploy, and this will create a monitor if I read this PR correctly. Would it?

**Comment by philipperolet** [comment]
This was not my understanding; I thought workers getting killed would result in an activity failure, but not a starttoclose timeout. The converse would surprise me and imho could be interpreted as a temporal bug. What would make you think that?

(note: another different kind of timeout, heartbeat timeouts, are another matter and could cause what you described)

**Comment by lasryaric** [comment]
I am positive that a deployment would cause either a heartbeat timeout or a startToCloseTimeout for activities that don't have a heartbeat timeout.

**Comment by lasryaric** [comment]
For context: once the worker pickup an activity to execute, if there is not heartbeating in place, the server has no way to know what is the status of the activity, hence the heartbeat and startToCLose timeout.

**Comment by philipperolet** [comment]
I understand your point, but wouldn't the server know the worker has been decomissioned? the temporal UI always shows us how many workers are up. So all activities related to a decommissioned worker have no reason to be marked as startToClose timeouted 

What makes me think it does not do that: I ran the check from prodbox to check it was fast (unrelated: it is, runs in ~1mn)
Had no starttoclose timeouts on all running workflows, while we did multiple deploys of connectors in the last 24 hours

I'm frisky about letting startToClose timeouts slide, especially since I had to investigate twice issues that ended up being caused by that, and it was a pain (multiple days of investigation)

**Comment by philipperolet** [comment]
Following IRL discussion, deploys do cause startToClose. Moving to a better solution just logging starttoclose failures as any other activity failure, see PR #5049

**Pull request closed without merging**
