### PR TITLE
Add: github copilot chat origin in messages

### PR DESCRIPTION
**Pull request by Fraggle**
## Description

Add: github copilot chat origin in messages

## Risk

None

## Deploy Plan

Deploy `front`

### CODE REVIEW

**Review by albandum — CHANGES_REQUESTED** [review]
Missing in: 
/dust/types/src/front/assistant/conversation.ts around line 70

**Comment by Fraggle** [comment]
>Missing in:
/dust/types/src/front/assistant/conversation.ts around line 70

It's not mandatory :) 
"email" is missing too for example, but i'll add :)

**Comment by albandum** [comment]
Yeah, let's try to keep consistency? (Maybe add email too ?:P)

**Review by albandum — APPROVED** [review]
Pre-approving with changes

**Pull request merged**
