### PR TITLE
Disable text/csv support in GDrive

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

In https://github.com/dust-tt/dust/pull/6153 we introduced support for `text/csv` files in Google Drive. Since then we have been observing `FATAL ERROR: Reached heap limit Allocation failed`. 

This PR disables it temporarily to see if this is the root cause.

image

### CODE REVIEW

**Review by JulesBelveze — APPROVED** [review]

**Comment by spolu** [comment]
@JulesBelveze this is a case of a small amount of code having a large blast radius. You should have made sure to monitor it thoroughly given the very large amount of CSVs that can be found in GDrive.

What's the plan moving forward so that we can have a clear message to users?

We can't stay in a limbo mode where we have some CSV but not others.

**Comment by JulesBelveze** [comment]
@spolu we are investigating if the error with the connector pods restarting was actually caused by CSVs. After disabling CSV processing it seems that they are not the issue.

**Comment by spolu** [comment]
Comment remains valid. I haven't seen any analysis of the impact of CSV imports, did I miss it?

**Comment by spolu** [comment]
Retrospectively we should likely have gated it like pdfs to workspaces as Google drive is full of generated CSVs at some of our users

**Comment by spolu** [comment]
By generated I mean periodically generated by automated recurrent workflows which is not desirable at all for us.

**Comment by JulesBelveze** [comment]
> Comment remains valid. I haven't seen any analysis of the impact of CSV imports, did I miss it?

Nop, didn't make any. Will do it once `connectors` is back in a healthy state.

> Retrospectively we should likely have gated it like pdfs to workspaces as Google drive is full of generated CSVs at some of our users

Understood.

**Comment by flvndvd** [comment]
I actually shipped on behalf of @JulesBelveze and monitored the initial hours post-release. This resulted in an API patch (PR https://github.com/dust-tt/dust/pull/6189). Everything appeared normal during the first few hours after the release.

**Comment by spolu** [comment]
ack 

FYI impact on the databases-store DB which seems somewhat reasonable. Still I think we should move to a flag :+1: 

2024-07-17-113659_1544x508_scrot

**Pull request merged**
