### PR TITLE
front: fix folders UX

### PR DESCRIPTION
**Pull request by spolu**
## Description

Fixes: https://github.com/dust-tt/tasks/issues/1027

Make the whole folder context item clickable instead of only the MoreIcon. This is more intuitive and aligns with websites.

## Risk

N/A

## Deploy Plan

- deploy `front`

### CODE REVIEW

**Comment by spolu** [comment]
PMRR

**Review by JulesBelveze — APPROVED** [review]

**Comment by spolu** [comment]
@JulesBelveze PTAL :pray:

**Comment by JulesBelveze** [comment]
LGTM thanks 😃

**Comment by JulesBelveze** [comment]
@spolu main reason I had the "Added by ..." on a new line was to limit having two lines in the `ToolTip` causing text to overflow. See screenshot below:

Screenshot 2024-07-08 at 11 06 45

cc @Duncid

**Comment by spolu** [comment]
Yes this happens on folders as well. This needs to be fixed in sparkle (hide the subElement in mobile resolution) and truncate the title

**Comment by spolu** [comment]
Created: https://github.com/dust-tt/tasks/issues/1035

**Pull request merged**
