### PR TITLE
add timeZone to input in chat

### PR DESCRIPTION
**Pull request by philipperolet**
@spolu As per your comments on slack, a basic PR so that chat answers with dates in the user's timezone

I'm also very clear on the code to change in chat-retrieval but not sure how to make the change
- is there a staging version of chat-retrieval & other dust-apps apps?
- are the specs are versioned in the dust repo or elsewhere -- to run PRs on those changes too
If answers are not yet, I can also work on that

### CODE REVIEW

**Comment by spolu** [comment]
There's no staging environment but the fact that each version of the app has its own hash lets you tweak the app without breaking the production environment.

So you can directly go change the `chat-retrieval` app in the `dust-apps` workspace and test this from your development machine. To update the hash in use you want to update `actions_reigstry.ts` file to point to the new hash.

Happy to chat IRL about that if needed :+1:

**Comment by spolu** [comment]
So all in all a full PR contains that change + a change to `actions_registry.ts` :+1:

**Comment by philipperolet** [comment]
2. Code change in chat-retrieval = the formatDate fn below and its calls
Screenshot from 2023-06-12 14-40-53

**Comment by philipperolet** [comment]
:warning: 3. it partially solves the issue only, e.g. discussions in slack docs are dated using UTC (and the doc title has an UTC date suffixed too), which cannot be easily adressed
Screenshot from 2023-06-12 14-37-30

**Review by spolu — APPROVED** [review]
LGTM

**Review by spolu — CHANGES_REQUESTED** [review]
As per IRL. We want to try reparsing the toLocalString client side when displaying the date of each document (date only not date+time)

**Comment by philipperolet** [comment]
i find it turns out to be either unstable or complex to do that without external libs. However, I finally found a simple way to get the ISO date & time  timezoned, so pushing that--the date format will be iso exactly as before, but with the user timezone
if that's fine by you

**Comment by philipperolet** [comment]
(that's the last commit pertaining to action_registry.ts)

**Review by spolu — APPROVED** [review]
Awesome. I checked the app LGTM

**Pull request merged**
