### PR TITLE
enh: add retrievedAt column on retrievalDocument

### PR DESCRIPTION
**Pull request by fontanierh**
fixing https://github.com/orgs/dust-tt/projects/3?pane=issue&itemId=40057879

step 1: this PR, adding the new `retrievedAt` field (nullable)
step 2: backfill the new column
step 3: update the code to only use retrievedAt
step 4: get rid of the timestamp column

### CODE REVIEW

**Review by spolu — APPROVED** [review]

**Review by spolu — CHANGES_REQUESTED** [review]
Actually the name is wrong we want timestampAt maybe since it’s not the retrieval but the timestamp of the doc right?

**Comment by fontanierh** [comment]
> Actually the name is wrong we want timestampAt maybe since it’s not the retrieval but the timestamp of the doc right?

Makes sense, how about `documentTimestamp` ? that will make it obvious

**Comment by spolu** [comment]
It should really be called timestamp I think :) but let's go with documentTimestamp for now and see if we motivate ourselves switching it back eventuallly

**Comment by fontanierh** [comment]
> It should really be called timestamp I think

@spolu  curious what the rationale is ? The (imo) vague name led me to think this was the timestamp of the retrieval, when it's really the timestamp of the document being retrieved

**Comment by fontanierh** [comment]
@spolu  changed to `documentTimestamp` and added a SQL migration

**Review by spolu — APPROVED** [review]

**Comment by spolu** [comment]
> > It should really be called timestamp I think
> 
> @spolu curious what the rationale is ? The (imo) vague name led me to think this was the timestamp of the retrieval, when it's really the timestamp of the document being retrieved

Well the model is called RetrievedDocument so it's a bit repetitive and by our convention the retrieval timestamp should be createdAt? but really documentTimestamp is fine :+1:

**Pull request merged**
