### PR TITLE
WIP feat: mailing for free trial reminder

### PR DESCRIPTION
**Pull request by fontanierh**

### CODE REVIEW

**Review by spolu — COMMENTED** [review]
So we really need to have N workflows vs just one?

looks like it will incur quite some operational cost to track these vs just one?

**Review by spolu — COMMENTED** [review]
It makes kind of sense to have one workflow per email but having a ton of sleeping workflows is not great IMHO

maybe one workflows that spawn child workflows when needed?

Even god forbid use production check for that main workflow ?

**Comment by fontanierh** [comment]
> So we really need to have N workflows vs just one?

If we have a single workflow, then it means we're tracking state in the DB (i.e "firstReminderEmailSentAt" and ""sencondReminderEmailSentAt" in DB). The idea here was to leverage temporal so we are "stateless".

> looks like it will incur quite some operational cost to track these vs just one?

What is the operational cost ?

> having a ton of sleeping workflows is not great IMHO

Curious why ? IMO the long-term sleep is the main appeal of temporal

**Comment by spolu** [comment]
State can be inferred from subscription start date no?

Not recording the email was sent is a bit brittle though I agree…

Having these long running workflows (days) is mostly a cost because we’ll have a lot of noise in our temporal queue. But if there is no reason to believe it has a temporal associated cost (using slots or whatnot) I’m def fine with it

**Comment by fontanierh** [comment]
> Having these long running workflows (days) is mostly a cost because we’ll have a lot of noise in our temporal queue. 

That's what temporal is for

> But if there is no reason to believe it has a temporal associated cost (using slots or whatnot) I’m def fine with it

Sleeping in an activity takes a slot. Sleeping in the workflow does not :)

**Comment by lasryaric** [comment]
My understanding of Temporal is that this is the main use case Temporal was written for.
In this example, the `sleep()` method would not make sense if it was a javascript sleep() because it would die on process crash or shutdown, but in this case it's a simple write to a DB and it's picked up by the Temporal engine at the appropriate time. I remember their demo use case to be exactly something like that:
- signup
- sleep
- send "revive"  email

Can't find it again but I clearly remember it.

**Comment by fontanierh** [comment]
> Not recording the email was sent is a bit brittle though I agree…

The more I think of it, the more I want to just have a CRON every hour that decides to send the email or not depending on state we have in the DB though... So "irstReminderEmailSentAt" and "secondReminderEmailSentAt". I find it more solid even though kind of sad that we wouldn't be leveraging temporal durable execution features to their fullest

**Comment by fontanierh** [comment]
The downside is it doesn't scale well because we'll have to add DB fields for every scheduled automated email we add

**Comment by spolu** [comment]
If Temporal is made for these long sleeps then let’s lean on it 👍

**Pull request closed without merging**
