### PR TITLE
Remove NangoConnectionId from Gdrive workflow state

### PR DESCRIPTION
**Pull request by lasryaric**

### CODE REVIEW

**Review by spolu — COMMENTED** [review]
Don't we need to bump the queue version since we're touching the workflows?

**Comment by lasryaric** [comment]
Yes - two more commits are coming.

**Comment by lasryaric** [comment]
>Don't we need to bump the queue version since we're touching the workflows?

I am actually not sure what to do here.

Since we don't have very long running workflows (except for full sync), bumping the queue or not is exposing us at the same risk of failing workflows.

If we bump: we will stop processing some existing workflows, but get no error.
If we don't bump, we'll get non deterministic errors.

Ideally we would have one commit with a worker for the old queue and the new queue.

Since we don't have that today, I would be in favor on not bumping the queue version, get an error for the non deterministic workflows and restart them manually.

**Comment by spolu** [comment]
But this means some workflow will old task to new code which is not the safest thing to do

I would bump the queue and manually kill the workflows + restart them (the fullSync ones if any)

**Comment by lasryaric** [comment]
>But this means some workflow will old task to new code which is not the safest thing to do no?

Gdrive and Slack were designed around webhooks with short lived workflows. So we never had that problem too much (compared to notion which has no webhook and have long lived workflows).

If we end up having an old workflow running on new code, we'll get an error and restart it manually.
It's easier to react on error I think. We have always deployed Slack and Gdrive like that with a very little error rate (their queue name is still v1).

**Comment by spolu** [comment]
Are you sure you'll get an error? How temporal knows there is a mismatch of code ?

**Comment by lasryaric** [comment]
I see them in dev and I saw a few in production when deploying new versions of Slack and Gdrive. I will double check this specific case locally and report back here.

**Review by philipperolet — DISMISSED** [review]
LGTM modulo the pending bumping decision / action

**Comment by lasryaric** [comment]
@spolu @philipperolet so after testing, we need to bump the version.
I thought changing workflow level code would trigger an error, but errors are not triggered when you only change the list of arguments to a function.
SInce workflows are compiled, I thought it would do a checksum version of the compiled workflows, but it actually looks at the activities order and throws a non deterministic error if the workflows calls activity in a new order.

**Comment by philipperolet** [comment]
Ack, GFM to merge after the bump (followed up by cleaning workflows)

PS: related [slack discussion](https://dust4ai.slack.com/archives/C05F84CFP0E/p1699214987133339) that triggered the PR

**Pull request merged**
