### PR TITLE
[Webcrawler] Handle websites taking long to crawl

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Some websites may take long to crawl. This is an issue when crawling exceeds 2 hours which is the activity limit for our crawl => the crawl is silently aborted and retried and hour later, and this repeats 15 times before we get an 'activity timeout' monitor (so 2 days)

See example in issue https://github.com/dust-tt/tasks/issues/883

This PR fixes https://github.com/dust-tt/tasks/issues/883. It:
1. clarifies the situation by raising a panic flag when the issue is clearly that the website is long to crawl.This is to ensure we don't crawl uselessely the same pages for 2 days before seeing an activity timeout, and avoids losing time in investigation (here a bunch of other errors were caused by the repeated crawl, etc.)

2. decreases max-requests-per-minute

3. moves the timeout to 4 hours which seems acceptable for slow websites with big pages (2 pages / minute maximum tolerated slowness for a 512 pages crawl)

4. Piggybacking on the PR, we disable logging frow crawlee to avoid leaking client data in datadog
Risk
---
na

Deploy
---
- deploy connectors
- Update eng runner runbook

### CODE REVIEW

**Comment by spolu** [comment]
@philipperolet can you add this https://dust4ai.slack.com/archives/C05F84CFP0E/p1718875681189169?thread_ts=1718874749.051429&cid=C05F84CFP0E while you're at it :pray: 

Thanks thanks!

**Comment by philipperolet** [comment]
> @philipperolet can you add this https://dust4ai.slack.com/archives/C05F84CFP0E/p1718875681189169?thread_ts=1718874749.051429&cid=C05F84CFP0E while you're at it 🙏

Did it, but as answered in thread, not sure disabling the log is the right thing to do, letting you check

**Comment by spolu** [comment]
I don't see anything in the thread?

**Comment by spolu** [comment]
Can you share your thoughts here as slack seems to be struggling a bit at least on my end for that thread. It keeps loading I see you face in the summary but not your message in the thread :pray:

**Comment by philipperolet** [comment]
pr
  [2 hours ago](https://dust4ai.slack.com/archives/C05F84CFP0E/p1718877070585859?thread_ts=1718874749.051429&cid=C05F84CFP0E)
hey! Added it to my pr but wondering -- how does this leak user data since it seems to be crawlee saying it crawls public webpages (not linked to workspaces / users in our logs)?





pr
  [2 hours ago](https://dust4ai.slack.com/archives/C05F84CFP0E/p1718877084468949?thread_ts=1718874749.051429&cid=C05F84CFP0E)
so after the fact, not sure we need to disable those


pr
  [2 hours ago](https://dust4ai.slack.com/archives/C05F84CFP0E/p1718877131481509?thread_ts=1718874749.051429&cid=C05F84CFP0E)
however, we can make the stripe monitor more stringent, so that it does not match errors from connectors and avoid the root issue


pr
  [2 hours ago](https://dust4ai.slack.com/archives/C05F84CFP0E/p1718877135533519?thread_ts=1718874749.051429&cid=C05F84CFP0E)
WDYT?

**Comment by philipperolet** [comment]
As discussed on thread, agreed to kill the log, not for a user data reason, but for a "those logs aren't useful" reason

**Review by lasryaric — APPROVED** [review]
LGTM

**Pull request merged**
