### PR TITLE
[Infra] Increasing front pods from 4 to 8

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
As an attempt to fix https://github.com/dust-tt/tasks/issues/859

Risk & deploy
---
Deploy front

### CODE REVIEW

**Comment by philipperolet** [comment]
PMRR

**Comment by spolu** [comment]
:money_with_wings:

**Comment by philipperolet** [comment]
Yes it's just a test. We will scale back down soon, when we solve the underlying issue

**Comment by lasryaric** [comment]
Discussed here:
https://github.com/dust-tt/tasks/issues/859#issuecomment-2167615695

**Comment by lasryaric** [comment]
LGTM although it's has already been reverted 👍

**Pull request merged**
