### PR TITLE
Updated landing

### PR DESCRIPTION
**Pull request by Duncid**
Sorry to bother you!
Here is an updated version.
It has particle animation, they react to scrolling.

Scrolling animations can be deactivated by setting "let hasScrollBehavior: boolean = true;" to false.

Obviously, this can wait for next week!

### CODE REVIEW

**Comment by spolu** [comment]
Will deploy to front edge so that we can admire it :-)

**Comment by Duncid** [comment]
Seem to work well, mobile and desktop

**Comment by spolu** [comment]
Yes beautiful

**Comment by spolu** [comment]
Leaving to @PopDaph to decide when to merge 👍

**Review by PopDaph — APPROVED** [review]

**Comment by PopDaph** [comment]
I removed the tsconfig thing and some debug, will deploy once green 🚀

**Pull request merged**
