### PR TITLE
clean-up: defaultNewResourcePermission

### PR DESCRIPTION
**Pull request by spolu**
Fixes https://github.com/dust-tt/tasks/issues/294

Remove `defaultNewResourcePermission` as it is unused.

In production we have 3 Connector (slack) that are not `read_write` but this information is not acted upon as per this PR:
https://metabase.dust.tt/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJxdWVyeSIsInF1ZXJ5Ijp7InNvdXJjZS10YWJsZSI6MTgsImZpbHRlciI6WyIhPSIsWyJmaWVsZCIsNDY0LG51bGxdLCJyZWFkX3dyaXRlIl19LCJkYXRhYmFzZSI6Mn0sImRpc3BsYXkiOiJ0YWJsZSIsInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==

Deploy:
- deploy connectors
- run init_db.sh
- deploy front
- remove the column from connectors

### CODE REVIEW

**Comment by fontanierh** [comment]
What do you mean by not acted upon ?

**Review by lasryaric — APPROVED** [review]
While I was not aware of the existence of this database field, I can confirm that Slack and Google Drive do not need the field `defaultNewResourcePermission` to work properly.

**Comment by spolu** [comment]
> What do you mean by not acted upon ?

The way the slack synchronization works today is that we don't listen to channel join webhooks and instead rely solely on connector permission edition.

When we set the permission (to `read_write`) this creates the SlackChannel object in the connectors handler and set its permission to `read_write`. It then triggers the resync workflows that takes the channels that changed permission as argument which in turn triggers the call to syncChannel which had an old upsert call which was now changed to an update call (update the name of the channel).

Since we had no way to change that value, it was always read_write (except for 3 connectors for whom, the product is broken since the data is not synchronized for the channels they click in the connectors permissions view).

**Comment by spolu** [comment]
The createConnector path didn't set it, and the slack connector was setting it to `read_write` by default: https://github.com/dust-tt/dust/pull/2940/files#diff-c9ac1afc79d5f738a1545e94aafb085ef19cd24da13425471115be0677c1cc0bL86

Interestingly the updateConnector code in types missed key value in the body of the update.

**Comment by spolu** [comment]
The only code that matter and that is preserved is this one: https://github.com/dust-tt/dust/blob/main/front/components/ConnectorPermissionsTree.tsx#L24-L27

**Comment by spolu** [comment]
Tested the full flow of creating a slack connection, adding channels

**Pull request merged**
