### PR TITLE
post upsert hooks -> post process hooks + add support for `onDelete` + implement `onDelete` for doc tracker

### PR DESCRIPTION
**Pull request by fontanierh**
quite tedious:

- rename `PostUpsertHook` into `DocumentsPostProcessHook` (update references / file names / directory names etc..)
- re-organize doc tracker code a bit
- add support for `onDelete` function on the `DocumentsPostProcessHook`
- implement `onDelete` for the doc tracker `updateTrackedDocuments`  hook
- add a temporal workflow that runs the `onDelete` when applicable

I needed the `onDelete` on doc tracker to cleanup the `TrackedDocument` table when a doc is deleted.

### CODE REVIEW

**Comment by fontanierh** [comment]
First 3 commits are just moving code around:
- https://github.com/dust-tt/dust/pull/844/commits/7ffbbe2f7ec8271fc04d7f30b6c0631b622155a6 and https://github.com/dust-tt/dust/pull/844/commits/4e62b12889a6b777f16445f1f9c46eb0ad519a0c are renaming the `PostUpsertHook` into `DocumentsPostProcessHook`
- https://github.com/dust-tt/dust/pull/844/commits/176d84cfe8a50e5ebe2bbe2a21506e669da28ab9 is re-organizing doc tracker code into multiple files


The actual functionality changes are in the last 2 commits

**Review by spolu — APPROVED** [review]
LGTM

**Review by PopDaph — APPROVED** [review]
Thank you, that's super clear! 🙇🏻‍♀️

**Comment by fontanierh** [comment]
Thanks for the reviews ! I'll probably need a followup PR to kill any potential running post upsert workflow for the doc that is being deleted

**Pull request merged**
