### PR TITLE
Flav/add pdf preprocessing

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

This PR adds the pdf preprocessing logic in the recently added file API. It uses the same logic and library as currently used in the client. Even though this library is not great as it does not support streaming, we will change it later on.

## Risk

This endpoint is not yet used.

### CODE REVIEW

**Review by lasryaric — APPROVED** [review]
LGTM

**Review by spolu — COMMENTED** [review]
Looks great!

We have from past experience figured that injecting the page number in the sections of the rendered object to upsert helps some use cases 

This points to the broader interesting question: do we want to support processed objects to be not only files but potentially structured Sections?

**Comment by flvndvd** [comment]
>This points to the broader interesting question: do we want to support processed objects to be not only files but potentially structured Sections?

This could be great! OOC, when uploading a PDF in a folder, is the page number considered as a hierarchy marker in our chunking algorithm?

**Comment by spolu** [comment]
> This could be great! OOC, when uploading a PDF in a folder, is the page number considered as a hierarchy marker in our chunking algorithm?

yessir

**Pull request merged**
