### PR TITLE
Fix toggle slack bot

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

Fixes https://github.com/dust-tt/tasks/issues/1372.

This PR exposes the connectors error when we fail to toggle the Slack chat bot.

ToggleSlackBot

### CODE REVIEW

**Comment by spolu** [comment]
What was the error in our case (that triggered the bug report) ?

**Comment by spolu** [comment]
Ah I see another dust workspace :+1:

**Comment by flvndvd** [comment]
> Ah I see another dust workspace 👍

Yes.

**Review by JulesBelveze — APPROVED** [review]
LGTM

**Pull request merged**
