### PR TITLE
Item Component refactor

### PR DESCRIPTION
**Pull request by Duncid**
Refactoring the Item component to make it way easier to understand and read and add functionality.
I plan this in two times:
- 1. New Item component and subcomponent, compatible with older Item
- 2. Removing older item once transition is complete

Deploy to front is on another PR.

### CODE REVIEW

**Review by spolu — COMMENTED** [review]
You're in for 2 steps of annoying refactor. Is it not better to directly modify Item and do the migration on front.

That just means that sparkle is "locked" until you do it in the sense that it can't be upgraded on front

**Comment by Duncid** [comment]
It's the other option indeed. Can do.

**Comment by spolu** [comment]
Your call :+1: You have the most context on the work involved.

**Comment by Duncid** [comment]
Cleaned old component and merging.

**Pull request merged**
