### PR TITLE
[Assistant Builder] Add tool name when not default

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Fixes https://github.com/dust-tt/tasks/issues/1807
image

image

Risks
---
na

Deploy
---
front

### CODE REVIEW

**Review by Fraggle — APPROVED** [review]
LGTM, don't you want to show it on the little box too ? (so we don't have to open to see it ?

**Comment by philipperolet** [comment]
> LGTM, don't you want to show it on the little box too ? (so we don't have to open to see it ?

Indeed

**Comment by Duncid** [comment]
How about making it part of the title?

Search - Custome_name

**Comment by philipperolet** [comment]
> How about making it part of the title?
> 
> Search - Custome_name

Had tried that, it looks very big with the header font size, see below. But actually, fine to do it like this if you prefer
Also, please take a look at updated cards in description :pray: 
image

**Comment by philipperolet** [comment]
Updated pics with @Duncid 's preferred solution

**Pull request merged**
