### PR TITLE
Add s-flex-wrap to Button.List + fix build

### PR DESCRIPTION
**Pull request by spolu**
- Fix a bunch of build warnings
- Adds `s-flex-wrap` to Button.List

### CODE REVIEW

**Comment by spolu** [comment]
In mobile view the button list on conversation new overflows

**Comment by spolu** [comment]
Screenshot from 2023-09-26 13-20-26

**Comment by Duncid** [comment]
@spolu how about an isWraping prop?
(If we often needs it)

**Comment by spolu** [comment]
Fine with starting with isWrapping will update and merge :+1:

**Pull request merged**
