### PR TITLE
feat: support OpenAI organization-id

### PR DESCRIPTION
**Pull request by fontanierh**
#216 

- only through external API
- as `openai_organization_id` in the config

### CODE REVIEW

**Review by spolu — CHANGES_REQUESTED** [review]
Since it’s a OAI specific thing it should go through `extras` (same as user parameter for the OpenAI API)

Otherwise looks good 👍

**Comment by spolu** [comment]
Yeah I think we should support it in the API only for now through extras vs credentials given that it’s not asked a lot.

Otherwise people might get scared by the extra setting I fear

**Comment by spolu** [comment]
wdyt?

I propose we start with extras (hidden) and then see if a full provider config is needed / useful

**Comment by fontanierh** [comment]
Ok to move to extras @spolu !

**Comment by fontanierh** [comment]
@spolu do we want to document somewhere `openai_user` and `openai_organization_id` ?

**Review by spolu — APPROVED** [review]
LGTM :ok_hand:

**Comment by spolu** [comment]
@fontanierh no need to to document for now IMHO let's just follow up on the Issue once I deploy next :+1:

**Pull request merged**
