### PR TITLE
DustAppRun UI

### PR DESCRIPTION
**Pull request by spolu**
Screenshot from 2023-10-11 16-44-22
Screenshot from 2023-10-11 16-44-44
Screenshot from 2023-10-11 16-44-53

In case of an app with no params

Screenshot from 2023-10-11 16-49-08

### CODE REVIEW

**Comment by spolu** [comment]
cc @Duncid FYI

**Review by PopDaph — DISMISSED** [review]
Looks good! 🤩 

Just a few nits, and this question: 
If the dust app always answers a block of json code, could we specify it to have syntax highlighting?

**Comment by spolu** [comment]
Applied feedback. Will create a task for syntax highlighting :+1:

**Comment by spolu** [comment]
Done here: https://github.com/orgs/dust-tt/projects/3/views/1?pane=issue&itemId=41270275

**Pull request merged**
