### PR TITLE
Fix: agentmessage streaming should show actions

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Moves the 'streamedAgentMessage' to the new format

### CODE REVIEW

**Review by spolu — APPROVED** [review]
I haven't yet reviewed the original PR but this looks reasonable. (Wondering how the type system didn't protect here?)

**Review by spolu — COMMENTED** [review]
Looked at the code. actions is likely already set on the message so when we add action here the type system is still happy I presume. cc @lasryaric 

Not sure there's a good way to get better type support here?

**Comment by lasryaric** [comment]
>Not sure there's a good way to get better type support here?

Apparently the type system can help you when using the simple form of setState:
```
const [message, setMessage] = useState<MessageType>(...)

setMessage({unknown_property: v}) // typescript error
```

but can't help you when using the "previous state form":
```
setMessage((previousState) => ({...previousState, unknownProperty:v})) // no Typescript error
```

Screenshot 2024-05-07 at 10 55 19

**Comment by lasryaric** [comment]
A practical solution is to add a satisfy or the return type of the setState() callback function:

```

setStreamedAgentMessage((previousState): AgentMessageType => {
    return { ...previousState };              ^^^^^^^^^
  });
```

**Pull request merged**
