### PR TITLE
Support mistral-small to create assistants

### PR DESCRIPTION
**Pull request by flvndvd**
This PR makes `mistral-small` available to build a custom assistant.

### CODE REVIEW

**Review by spolu — COMMENTED** [review]
As per IRL path is:
- replace @mistral mistral 7b by @mistral-small mistral-small and introduce @mistral-medium for paid accounts
- Move to mistral-small or mistral-medium for assistant creation
- migrate assistants using mistral  7b to use mistral small
- remove all traces of mistral 7b

**Comment by spolu** [comment]
What’s the state of that PR?

**Comment by flvndvd** [comment]
> As per IRL path is:
> 
> * replace @Mistral mistral 7b by @mistral-small mistral-small and introduce @mistral-medium for paid accounts
> * Move to mistral-small or mistral-medium for assistant creation
> * migrate assistants using mistral  7b to use mistral small
> * remove all traces of mistral 7b

As per IRL path is:

- ✅ replace @Mistral mistral 7b by @mistral-small mistral-small and introduce @mistral-medium for paid accounts
- 🏃 Move to mistral-small or mistral-medium for assistant creation _(This PR)_
- ✅ migrate assistants using mistral 7b to use mistral small _(but users can still create a new assistant with Mistral 7b until this PR is out)_
- [not started] remove all traces of mistral 7b

**Comment by spolu** [comment]
🙏

**Comment by flvndvd** [comment]
✅  Move to mistral-small or mistral-medium for assistant creation (https://github.com/dust-tt/dust/pull/2958)

**Comment by flvndvd** [comment]
Closing this PR as all action items have been addressed on separate PRs.

**Pull request closed without merging**
