### PR TITLE
Improve email invitation

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

See https://github.com/dust-tt/dust/issues/4055.
🧑‍🎨 [Figma](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?node-id=3928%3A157814&mode=dev)

This PR improves the way we send invitation emails by relying on the Sendgrid dynamic templates. Until today, our emails are raw, they don't have any design and look a bit cheap.

This PR enhances the invitation email process by relying on Sendgrid's dynamic templates. Previously, our emails were plain text and lacked some design.

🐒 Tested locally, works well.

It looks like this (I'll see with @Duncid for the design):
image

## Deploy Plan

- [ ] Add env variable `SENDGRID_INVITATION_EMAIL_TEMPLATE_ID`.

### CODE REVIEW

**Comment by flvndvd** [comment]
From @Duncid:
> that's completely fake — no change on today's content today.

I suggest we still invest in adding some templates on our emails 🙃.

**Comment by Duncid** [comment]
> I suggest we still invest in adding some templates on our emails 🙃.

Fair question. I have mixed feelings about it, taking it to the team see what the word on the street is.

**Comment by spolu** [comment]
@flvndvd do you have a strong feeling for templated emails vs plain text ?

**Comment by spolu** [comment]
I love plain text emails but I’m super biased…

It’s almost a marketing question IMHO :-)

**Comment by Duncid** [comment]
@flvndvd here is a layout / copy proposal reviewed by @gabhubert !

image

**Comment by flvndvd** [comment]
> @flvndvd do you have a strong feeling for templated emails vs plain text ?

Even though I do like raw text, I think adding a touch of Dust's visual to our templates would be great for building our brand in the enterprise world. Nothing too fancy though. Let's keep it clean and professional!

**Comment by flvndvd** [comment]
Updated:

image

**Review by spolu — APPROVED** [review]
LGTM 👍

**Comment by Duncid** [comment]
@flvndvd can you fix the layout?
Dust logo is super big. See screenshot.

**Comment by flvndvd** [comment]
Better?
image

**Comment by Duncid** [comment]
Yes !
Hard to tell from the screenshot, but either the text is too small or the logo and button are too big (factor of 1.5 I would say)

**Pull request merged**
