### PR TITLE
[sparkle] Take focus in modal over close button

### PR DESCRIPTION
**Pull request by tdraier**
fixes: https://github.com/dust-tt/tasks/issues/1679

## Description

Glitch appears when the close button takes focus on modal open. Give the focus to modal content instead (and remove the focus outline)

### CODE REVIEW

**Review by JulesBelveze — COMMENTED** [review]
Isn't this gonna conflict with the other focus we have (idk if we do have some actually)  ?

**Comment by tdraier** [comment]
> Isn't this gonna conflict with the other focus we have (idk if we do have some actually) ?

which one ? (in my cas the close button was taking the focus)

**Comment by JulesBelveze** [comment]
I mean, let's say I want to add focus on an `Input` inside a modal, I guess they'll be conflicting right?

**Comment by tdraier** [comment]
> I mean, let's say I want to add focus on an `Input` inside a modal, I guess they'll be conflicting right?

If you have an explicit focus it should take over the simple tabIndex=1. I can also use tabIndex=32767 , which will come before the button but after any other positive tabIndex value. Do you have an example ?

**Review by JulesBelveze — APPROVED** [review]
Seen IRL, LGTM -> planning on moving to radix sheet soon anyways

**Pull request merged**
