### PR TITLE
Basic Action detail rendering for include_file

### PR DESCRIPTION
**Pull request by spolu**
## Description

Add file title on the action so that we can render it in the conversation
Basic action rendering
Fixes some typing issues

## Risk

N/A behind flag. migration!

## Deploy Plan

- run  migration
- deploy `front`

### CODE REVIEW

**Review by Fraggle — APPROVED** [review]
LGTM
Nit: fileTitle => fileName ?

**Comment by spolu** [comment]
Re your nit, it's called title everywhere so avoiding the introduction of a new "noun"

**Comment by Fraggle** [comment]
> Re your nit, it's called title everywhere so avoiding the introduction of a new "noun"

I came with this context.

image

**Comment by spolu** [comment]
By the time I pull it from the ContentFragment it's called title :/ In any case easy to refactor

**Pull request merged**
