### PR TITLE
Add zendesk logo to sparkle

### PR DESCRIPTION
**Pull request by albandum**
## Description

Add zendesk logo to sparkle

### CODE REVIEW

**Review by JulesBelveze — COMMENTED** [review]
Not sure why there are so many changes...

**Comment by albandum** [comment]
> Not sure why there are so many changes...

Linter made them 🤷

**Comment by JulesBelveze** [comment]
Let's just rollback and left the files as they were no?

**Comment by albandum** [comment]
Replaced by https://github.com/dust-tt/dust/pull/6577

**Pull request closed without merging**
