### PR TITLE
Support more dates format in Tables

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

See https://github.com/dust-tt/tasks/issues/1044.

This PR improves date coverage for tables we upsert by adding support for two additional popular date formats, which are sometimes the default ones.

### CODE REVIEW

**Review by fontanierh — CHANGES_REQUESTED** [review]
Not bullish. These date formats are ambiguous so we could be mis-parsing dates.

**Comment by fontanierh** [comment]
We can either:
- keep those as strings, and let the model (with proper instructions) parse the dates in SQL at query time
- parse using both EU and US format. If both work, just keep a string. If only one works then we can keep that parsing method. But that will not work for incremental updates so I would prefer not doing this (it's going to be a mess with notion DBs)

**Comment by flvndvd** [comment]
> Not bullish. These date formats are ambiguous so we could be mis-parsing dates.

🤔 The problem is that testing different Google workspaces, these formats are often the default. As we both know, querying on dates when the field is not recognized as a date can lead to poor results. Any other suggestions?

**Comment by fontanierh** [comment]
> Any other suggestions?

We should recommend people to prompt correctly. We could automatically suggest it if there are string columns that look like dates.

**Comment by flvndvd** [comment]
> > Any other suggestions?
> 
> We should recommend people to prompt correctly. We could automatically suggest it if there are string columns that look like dates.

Let me try prompting.

**Comment by fontanierh** [comment]
> These formats are often the default

If we are talking about an actual date column in a gsheet, the gsheet API should give us a date object, in which case our gdrive connector code could translate the date into an non-ambiguous format.

**Comment by fontanierh** [comment]
> Let me try prompting.

Just to clarify, I don't mean changing our dust app. I mean suggesting people (builders) to add in their assistant instructions that column X is a date column in US format for example. this 100% work and has been extensively tested already

**Pull request closed without merging**
