### PR TITLE
Sparkle: Page.P returns a div

### PR DESCRIPTION
**Pull request by PopDaph**
We probably shouldn't be putting div inside a Page.P but we all know it will happen again, so better handle it.

### CODE REVIEW

**Comment by Duncid** [comment]
Umm, not convinced here.
I think it's better to raise an error than let divs piling up in what's supposed to be a paragraph.

**Comment by PopDaph** [comment]
This: https://github.com/dust-tt/dust/blob/main/front/pages/w/%5BwId%5D/builder/data-sources/managed.tsx#L607

**Comment by Duncid** [comment]
Yes exactly, that should not be happening and is defeating the purpose of having Page.P.

A paragraph is a paragraph, we should thus not change the text size, and each div should be its own paragraph).
So I confirm we don't want to do this.

In this case what we want is add a size prop to Page.P (default size="md", corresponding to a text-base, new size "sm" corresponding to a "text-sm") so no need of the div setting text style, and then we want 4 "Page.P", one per paragraph.

**Comment by PopDaph** [comment]
Fine by me, I think it will happen again and this was a pit of success but I agree with you on the theory.

**Pull request closed without merging**
