### PR TITLE
Restructure Qdrant data source in core

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

This PR sets the stage for adding support for shadow embedders in the data source configuration, making this change invisible outside the data source code. To achieve this, we need to restructure certain components, which is the focus of this PR.

This PR overhauls the existing Qdrant implementation. As we increasingly need to incorporate more logic related to data source configuration (such as shadow write clusters and shadow embedders), this PR introduces a wrapper around the existing `DustQdrantClient`. This wrapper encapsulates the context, including the data source's `internal_id` and the `embedder_config`. Most methods have been migrated from `DustQdrantClient` to `QdrantClientWithConfig` to use the wrapped context.

The wrapper enables cleaner method signatures, as methods no longer need to take DataSource and EmbedderConfig as parameters. This leads to simpler and more readable method definitions. Since the data source remains consistent throughout the code, there's no need for the flexibility to pass different data sources.

Additionally, this PR refactors all existing logic related to cluster shadow writing, moving it to the DataSource level.

## Risk

Pretty risky but well tested locally. Safe to rollback.

### CODE REVIEW

**Comment by spolu** [comment]
Wait I don't grok it. I thought we said we would just move from &DataSource to internal_id and embedder as arguments of the DustQdrantClient functions without further change in qdrant.rs?

**Comment by flvndvd** [comment]
> Wait I don't grok it. I thought we said we would just move from &DataSource to internal_id and embedder as arguments of the DustQdrantClient functions without further change in qdrant.rs?

Yep I extracted the changes from my previous branch, it's not yet ready to review 😛.

**Comment by spolu** [comment]
Roger that

**Comment by flvndvd** [comment]
Superseed by https://github.com/dust-tt/dust/pull/5359.

**Pull request closed without merging**
