### PR TITLE
New Design Assistant Thoughts

### PR DESCRIPTION
**Pull request by PopDaph**
### Task

Task: https://github.com/dust-tt/tasks/issues/1055
Todo: New design for Assistant Thought.

From Figma: 
<kbd>
image
</kbd>

### Done

It's a bit annoying to reduce the text size because the text is going through `RenderMessageMarkdown`.
I added an optional `textSize` attribute for this component, and we reduce textSize & paddings in paragraphs & li. 

<kbd>
Screenshot 2024-08-27 at 10 14 10
</kbd>

Here's what a list looks like: 
<kbd>
Screenshot 2024-08-27 at 10 16 33
</kbd>

## Risk

Can be rolled back.

## Deploy Plan

Deploy front.

### CODE REVIEW

**Review by spolu — APPROVED** [review]
Should we tweak anthropic prompt to generate them more often vs raw text coming before each action?

**Comment by spolu** [comment]
If I remember correctly we currently have a prompt that asks anthropic to not use the XML tags that mark assistant thoughts and instead as much as possible just include raw text which do get generated before the action but is not marked as assistant thoughts?

**Comment by PopDaph** [comment]
> If I remember correctly we currently have a prompt that asks anthropic to not use the XML tags that mark assistant thoughts and instead as much as possible just include raw text which do get generated before the action but is not marked as assistant thoughts?

I confirm it's now very hard to get Assistant Thoughts (only @\god does it but his prompt specifies to use a <thinking> before using a tool). I don't know if we did anything to prevent thoughts, after a quick search I did not find any meta prompt for Anthropic.

**Comment by PopDaph** [comment]
> Should we tweak anthropic prompt to generate them more often vs raw text coming before each action?

I'm in favor of that, thoughts increase the trust I have in an assistant answer, but not sure it's a popular opinion I remember we had some complains about thoughts being "annoying".

**Comment by spolu** [comment]
Looking for the prompt...

**Comment by spolu** [comment]
Mmmmh can't see it anymore. Digging into runs but I broke the outputs of runs when viewing them with my work yesterday. So will have to fix that first :)

**Comment by spolu** [comment]
(done here: https://github.com/dust-tt/dust/pull/6930)

**Comment by spolu** [comment]
I don't think we have any anymore.... huh

**Comment by spolu** [comment]
We could prompt to use the tag when thoughts are needed

**Comment by PopDaph** [comment]
Adding a card in Olympus

**Pull request merged**
