### PR TITLE
feat(core): allow specifying hash of latest version to retrieve

### PR DESCRIPTION
**Pull request by fontanierh**
When listing the versions of a document (in reverse-chron order), it can be useful to specify the hash of the latest version to retrieve.
This allows to:
- not have broken pagination if a new version is added while iterating on result pages
- quickly obtain the version right before a given hash (use case required for Doc Tracker and Events post upsert hooks)

### CODE REVIEW

**Review by spolu — CHANGES_REQUESTED** [review]
LGTM 👍

But we probably want a new index for that. To be checked but I believe they get automatically created at startup.

**Comment by fontanierh** [comment]
> But we probably want a new index for that. To be checked but I believe they get automatically created at startup.

Good point ! Adding

**Comment by fontanierh** [comment]
@spolu  added the indexes, and I confirm they get automatically added when restarting the app

**Review by spolu — APPROVED** [review]
LGTM

**Pull request merged**
