### PR TITLE
Fix: agentMessage shows action rendering during streaming, improved

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Following #5004

Adapted to support multi-actions

### CODE REVIEW

**Review by spolu — APPROVED** [review]
Not sure I understand why we still have mono actions?

**Comment by lasryaric** [comment]
>Not sure I understand why we still have mono actions?

We added an array of actions backend side only with [this](https://github.com/dust-tt/dust/pull/4990) PR, and adjusted the front-end to always use actions[0].
Front-end will be handled in a different PR.

**Comment by lasryaric** [comment]
This PR would indeed be better indeed better in a multi actions world, but for now only the data structure is in place. All these agent messages are still mono actions.

**Comment by lasryaric** [comment]
@fontanierh can you give us your opinion on this PR please?

**Review by spolu — APPROVED** [review]
I now understand the code. The event has only one action but the AgentMessage can have multiple this LGTM

**Comment by lasryaric** [comment]
True but for now we decided to keep mono action support on the UI side. No
big deal but this PR is like a no-op for IMHO.

**Comment by philipperolet** [comment]
yes, the PR is clearly refactoring and does not change existing behaviour. But it makes sense for the following reason IMHO.

Mono-action is kept on the UI, but with clear marks so that we prepare for multi-actions, e.g. with "deprecatedXXX" functions, in the rest of the code.

Previous state with my pr #5004  was silently mark = bullet in the foot for future us (highly likely we miss the change), which was an issue

We could either 1. clearly mark it, creating deprecatedXXX function for it or 2. directly write the code for multi actions

Since in this case, 2. was fast and obvious, I went for 2.

**Pull request merged**
