### PR TITLE
Trying to improve templates UI

### PR DESCRIPTION
**Pull request by Uzay-G**
Remaining issues:

- hover is creating problems with resizing of flex elements shrinking and I'm not sure how to do this properly
- should figure out maybe how to have more colors but tailwind doesn't support me dynamically creating new colors because they're not added by default unless in the initial render
- templates make the stuff underneath go down, not sure how to structure the design

### CODE REVIEW

**Comment by spolu** [comment]
> templates make the stuff underneath go down, not sure how to structure the design
easy fix is to increase the # of lines of the textarea

**Comment by Uzay-G** [comment]
That pushes down the other (important) stuff though, what are you thinking in terms of maybe putting that to the side?

**Comment by spolu** [comment]
Let’s spend some time tomorrow morning on this 👍

**Comment by spolu** [comment]
@Uzay-G will merge this iteration and we can take it from there

**Pull request merged**
