### PR TITLE
Ensure the CSV is valid before enqueuing the table upsert.

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

In https://github.com/dust-tt/dust/pull/5695, we've transitioned the table upsert process to a dedicated worker/queue. 

However, we overlooked an important aspect: ensuring the CSV is valid before it's enqueued. This PR introduces a validation check before enqueuing to prevent non-actionable failures in the activity and instead fail the HTTP query if the CSV is invalid.

### CODE REVIEW

**Review by philipperolet — COMMENTED** [review]
Thanks ! Just a check: we moved that part to an upsert queue to avoid long sync requests which caused a bunch of issues.
Is CSV validation fast on large csvs? Because if it was the long part of the upsert process, moving it back to connectors would defeat the point

**Comment by flvndvd** [comment]
> Thanks ! Just a check: we moved that part to an upsert queue to avoid long sync requests which caused a bunch of issues. Is CSV validation fast on large csvs? Because if it was the long part of the upsert process, moving it back to connectors would defeat the point

I won't say it's "fast" but the bottleneck is definitely on the API request made on core. Core needs to run many checks to transform into a proper table. I'll make sure to monitor once it's out.

**Review by philipperolet — APPROVED** [review]

**Comment by philipperolet** [comment]
:+1: Would catching the invalid error and finishing the activity be an interesting alternate solution then?
Just a suggestion, approving :)

**Comment by flvndvd** [comment]
> 👍 Would catching the invalid error and finishing the activity be an interesting alternate solution then? Just a suggestion, approving :)

I'm not a fan as we should always ensure that the sole reason for an upsert activity to fail is an issue that requires actions from engineering.

**Comment by philipperolet** [comment]
What I suggest would not be an activity failure. It would be an activity success (with a log), saying "not upserting because invalid". The workflow would finish

**Comment by philipperolet** [comment]
Although, ofc if the `rowsFromCsv` is actually just a few 10s of milliseconds the best solution remains to do it on connectors rather than on upsert queue

**Comment by flvndvd** [comment]
I see but then it's misleading cause on the connector side we will assumed that the table was upserted and display it in the UI.

**Comment by philipperolet** [comment]
yes, that would require handling. Let's just see, maybe `rowsFromCsv` is actually not slow at all, in which case there's no need to look further

**Pull request merged**
