### PR TITLE
[Meru][Easier Onboarding] Allow admins to send multiple invites

### LINKED ISSUE #4419: [Meru] [Easier onboarding] Allow multiple emails input
Figma is [here](https://www.figma.com/file/QOxHwppG64GtPocpDhS6Y7/Product?type=design&node-id=4384-92304&mode=design&t=WrZ0pj6vtkCACHAx-4), and will be done in 3 steps, this is step 2 (self explanatory)

### PR DESCRIPTION
**Pull request by philipperolet**
## Description

Fixes #4419 

Checks email validity before sending. Multiple paths are possible depending on the email list. Some users:
A. may already be in the workspace, with the same role as the one proposed for invitation,
B. may already be in the workspace, with a different role,
C. may be revoked from the workspace,
D. may not be in the workspace, but already invited,
E. may be first-time invitee

Here's how each is handled, after discussion with @Duncid (& @lasryaric for case D)
- A. is silently ignored
- B & C yield a confirmation popup (see screenshot); if confirmed, all invitees in case B & C are switched to the role chosen for invitation;
- D. is reinvited with the role chosen (previous invitation updated, email re-sent);
- E gets a regular email invitation

### Tech Note
- this PR also bumps sparkle for front, switching InstructionsScreen to the new TextArea component

#### State before inviting:
Screenshot from 2024-03-28 16-56-20

#### Invite modal
Screenshot from 2024-03-28 16-57-08

#### Warning screen
Screenshot from 2024-03-28 16-57-27

#### State after inviting
Screenshot from 2024-03-28 16-57-49

### CODE REVIEW

**Comment by spolu** [comment]
What's going on with the package-lock.json here?

**Comment by philipperolet** [comment]
> What's going on with the package-lock.json here?

Will investigate

**Review by spolu — APPROVED** [review]

**Comment by Duncid** [comment]
Looking great, thank you for the work!

@philipperolet this type of modal should not be used.
It's either a Dialog or a drawer!

**Comment by philipperolet** [comment]
@Duncid Absolutely, I agree but the refactoring is outside the scope of the PR

**Pull request merged**
