### PR TITLE
Updated landing

### PR DESCRIPTION
**Pull request by Duncid**
Here is a first version of the updated landing page:
- New font type
- New colors
- New copy

(FYI @dust-tt/product-team)

### CODE REVIEW

**Comment by spolu** [comment]
Looks rad :+1: Good to ship once the linter is happy. You can ask engineering for help for that :+1:

**Comment by spolu** [comment]
company's knowledge breaks the mobile flow
Screenshot from 2023-07-28 09-29-28

should be a small fix

**Comment by Duncid** [comment]
@spolu fixed!

I'll be working on integrating the new anim and more visual effects.

**Comment by spolu** [comment]
@fontanierh | @PopDaph | @philipperolet | @lasryaric can you help with the linting? 🙏

LGTM

@Duncid you want to setup a linter in your code env at save time 👍

**Comment by spolu** [comment]
Exciting!!

**Review by PopDaph — APPROVED** [review]

**Comment by PopDaph** [comment]
I fixed the lint errors and merged. I'll deploy!

**Pull request merged**
