### PR TITLE
Hotfix: requested group ids arrays must be of same length

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---
Fixes issue from [this kind of
monitor](https://dust4ai.slack.com/archives/C05F84CFP0E/p1732945133294399)

The longer term fix would be to store requested ids differently:
- either as string[] with comma-separated values;
- or as a JSONB object

Risks
---
na

Deploy
---
front

### CODE REVIEW

**Comment by philipperolet** [comment]
PMRR

**Comment by flvndvd** [comment]
This is weird 🤔. Where does it happen? Conversation?

**Comment by philipperolet** [comment]
yes (check the link in the pr description)

**Comment by spolu** [comment]
Thanks! Lets dig into it and find a proper solution on Monday 👍

**Comment by flvndvd** [comment]
Will take care of it.

**Comment by flvndvd** [comment]
Tracked [here](https://github.com/dust-tt/dust/issues/9043).

**Pull request merged**
