### PR TITLE
Flav/core function calls history

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

See https://github.com/dust-tt/dust/issues/4968.

This pull request augments the chat block to support the inclusion of historical messages with `function_calls`, as well as the ability to pass function call results. This PR only focuses on OpenAI.

To maintain compatibility with the existing behavior, a workaround has been implemented.
OpenAI has introduced a new `tool` role for relaying tool results, which in our case, corresponds to `function_calls`. We still need to support the `function` role, as it's used by our dust apps for `content_fragment`. The `tool` role is intentionally not exposed, instead, some logic is incorporated in OpenAI side to automatically map the `function` role to `tool` when a `function_call_id` is provided.

## Risk

Worst case it breaks content fragment/action on dust app that relies on OpenAI. Safe to rollback.

### CODE REVIEW

**Review by spolu — APPROVED** [review]
Looks very reasonable.

Where is the tool_id passed in the OpenAI API? The Anthropic API?

The current position at the top of the ChatMessage seems weird?

**Comment by flvndvd** [comment]
> Looks very reasonable.
> 
> Where is the tool_id passed in the OpenAI API? The Anthropic API?
> 
> The current position at the top of the ChatMessage seems weird?

ATM, the `tool_id` is only passed to OpenAI, and you can find the relevant logic for this process in this GitHub diff ([here](https://github.com/dust-tt/dust/pull/5029/files#diff-ab3a1b57a59f143093e7f35ced019225079955b196f7a9cac8fd6792f3d71c9dR344)).
The reason for `tool_id` to live at the top level of the `ChatMessage` structure is to establish a consistent API among all the providers. Anthropic, for instance, returns multiple content fragments (including CoT), and we currently have to consolidate all this data into a single `ChatMessage`.

It will look like this on the API:

```
                "messages": [
                    {
                        "role": "user",
                        "content": "what is the weather going to be like in San Francisco and Glasgow?"
                    },
                    {
                        "role": "assistant",
                        "function_calls": [
                            {
                                "arguments": "{\"location\": \"San Francisco\", \"format\": \"celsius\", \"num_days\": 4}",
                                "id": "call_rZFqNJk0NlA5UMds5gCW9JGx",
                                "name": "get_n_day_weather_forecast"
                            },
                            {
                                "arguments": "{\"location\": \"Glasgow\", \"format\": \"celsius\", \"num_days\": 4}",
                                "id": "call_Q9CJQNGBtvmeUAj48fwsq6ay",
                                "name": "get_n_day_weather_forecast"
                            }
                        ]
                    },
                    {
                        "role": "function",
                        "content": "It will be 10 degrees farhenheit",
                        "function_call_id": "call_rZFqNJk0NlA5UMds5gCW9JGx"
                    },
                    {
                        "role": "function",
                        "content": "It will be 20 degrees celsius",
                        "function_call_id": "call_Q9CJQNGBtvmeUAj48fwsq6ay"
                    }
                ]
```

Any concern on your side?

**Comment by spolu** [comment]
This looks very reasonable.

Do Mistral/Anthropic support multiple function/tool messages?

Even if not we can adapt based on that interface I presume, so LGTM

**Comment by flvndvd** [comment]
> Do Mistral/Anthropic support multiple function/tool messages?
Yep they do, PRs are coming shortly.

**Pull request merged**
