### PR TITLE
Properly delete all related google drive resources

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

Delete google drive associated resources.

### CODE REVIEW

**Review by spolu — APPROVED** [review]
Are we sure they are all indexed?

**Review by lasryaric — COMMENTED** [review]
Lets add the foreign key on GoogleDriveConfig please 🙏

**Comment by flvndvd** [comment]
> Are we sure they are all indexed?

Yes

**Comment by flvndvd** [comment]
> > Are we sure they are all indexed?
> 
> Yes

Will do in a follow up PR, struggling with Sequelize.

**Pull request merged**
