### PR TITLE
fix: move skip before the fetch

### PR DESCRIPTION
**Pull request by fontanierh**

### CODE REVIEW

**Review by spolu — APPROVED** [review]
LGTM

**Comment by spolu** [comment]
Needs restart?

**Comment by spolu** [comment]
Or maybe just deploy?

**Comment by fontanierh** [comment]
Will just need the deploy, but not urgent we can let the current workflows finish with the current code

**Comment by spolu** [comment]
Can’t we just deploy since it does not touch the workflow and have the current workflow pick it up?

**Pull request merged**
