### PR TITLE
enh(github conn): use the last update time as Doc timestamp

### PR DESCRIPTION
**Pull request by fontanierh**
related to https://github.com/dust-tt/tasks/issues/13 -- we want to use the "udpated At" timestamp instead of "created At" as the timestamp we pass to upsert.

⚠️ : requires a GH connector full resync

### CODE REVIEW

**Comment by spolu** [comment]
Do you plan a full resync? If so let's wait for this: https://github.com/dust-tt/dust/pull/1192#pullrequestreview-1606447810 to merge and deploy

**Review by spolu — APPROVED** [review]

**Comment by fontanierh** [comment]
> Do you plan a full resync? If so let's wait for this: https://github.com/dust-tt/dust/pull/1192#pullrequestreview-1606447810 to merge and deploy

Yes it should be relatively quick for GH connectors to full resync

**Comment by spolu** [comment]
status?

**Review by lasryaric — APPROVED** [review]

**Comment by fontanierh** [comment]
@spolu 
> status?

Was waiting on #1192, since it's now merged I'm rebase + merging this one and running a full resync for github conns

**Pull request merged**
