### PR TITLE
Conversation - Layout Emojis on right column

### PR DESCRIPTION
**Pull request by PopDaph**
This PR puts back the emojis on the right column, requested by Ed here: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1696433064220129

Because the emojis sections won't have the same size depending on wether someone has reacted, I had to move to a grid layout for the message: 
- First column for avatar: I decided to display the avatar in xs in mobile, which work really well.
- Second column for the message content. 
- Third column for all the buttons. 

Please note that the Icon used for the new emoji button is not final, just waiting for Ed to merge one of his PR. 

### On Web
Capture d’écran 2023-10-04 à 20 54 33

### On Mobile
Capture d’écran 2023-10-04 à 20 54 40

### CODE REVIEW

**Comment by spolu** [comment]
Looks great but I think emojis take way too much space still:
- Too much visual space, there are emojis everywhere even if nothing was emoji-ed
- Too much horizontal space: this is hurting the main product experience IMHO

Let's discuss tomorrow :+1: with all stakeholders in the same room cc @gabhubert @Duncid 

As an indication below 2 screenshots of the same convo before/after to demonstrate the horizontal loss :)

Screenshot from 2023-10-04 21-23-56
Screenshot from 2023-10-04 21-24-30

**Comment by spolu** [comment]
And looking at these screenshots I really feel like there are emojis all over the place which I find distracting and communicating a vibe a bit at odd with productivity

**Comment by spolu** [comment]
@PopDaph the code looks great nonetheless. Thanks for pushing this. We're a few tweaks away I'm sure :+1:

**Comment by spolu** [comment]
Note for self :grimacing: 

- I think the right hand commands should always be vertically layed out to maximize conversation space. That's the main goal of the product it should be front and center.
- I think we should remove default emojis. It's just too distracting. What is the goal of having them?
- Why not a simple +emoji at the bottom? What is wrong with that?

**Comment by PopDaph** [comment]
@spolu I agree! I preferred the old layout. 
There are several things we can do: displaying the emojis buttons on hover to the message, and displaying them only for agent messages. This could be a good and not expensive next step. WDYT?

**Comment by spolu** [comment]
Let's have a chat today to converge :+1: ?

**Comment by Duncid** [comment]
Here is a proposal that addresses the horizontal space:
image

The loss of space has no reason to be though, the modifiction of buttons on the side should not change the width of the core of the message:

image

**Comment by spolu** [comment]
It's a bit more complex than that as you want a good continuity of the layout as you decrease your screen size. Right now we use w-4xl which is aligned with the lg responsive modifier I believe such that when we reach lg everything starts to compress nicely. One possibility would be to push to 5xl and have a change of layout at the lg boundary... Nothing impossible but just a departure from the uniform use of max-w-4xl everywhere.

**Comment by Duncid** [comment]
# Use of space

IMO the right angle here is to be smarter with space.
We're not tight today, the space is large (almost too much for lines of texts), we can have strategies for smaller screens (really doing responsive and not just resizing, for instance putting some interactions behind menus etc…)

# Emoji overload

It's really a choice.
They are visible, but it's also attracting attentions to them.
An easy way to reduce overload would be to go back to the original design:
image


So something like:
image

image

**Comment by spolu** [comment]
I agree we can work out the space problem.

As for darwing attention to emojis how do you feel about a hover which seems to be the slack way of handling that?

**Pull request merged**
