### PR TITLE
Cookie Banner homepage

### PR DESCRIPTION
**Pull request by PopDaph**
This is probably the most basic we can do. 
It does not move. 🏃🏻‍♀️ 
It load GA only if accepted. It is displayed again if we refresh.

Review with hidden whitespaces: https://github.com/dust-tt/dust/pull/2400/files?diff=split&w=1

Capture d’écran 2023-11-06 à 16 25 56

### CODE REVIEW

**Review by spolu — DISMISSED** [review]
Looks great!

Left minor comments on content

**Comment by PopDaph** [comment]
Prettified it with Ed: 
Capture d’écran 2023-11-06 à 17 11 18

**Review by spolu — DISMISSED** [review]
\o/

**Comment by PopDaph** [comment]
Capture d’écran 2023-11-06 à 17 14 11

**Comment by spolu** [comment]
Thanks! :100:

**Review by spolu — APPROVED** [review]

**Pull request merged**
