### PR TITLE
typo propagation

### PR DESCRIPTION
**Pull request by philipperolet**

### CODE REVIEW

**Comment by philipperolet** [comment]
in order to have to redeploy core only once, I can also add the correct field in the upsert 
didn't do it directly since it may be more risky to deploy; tell me

**Comment by spolu** [comment]
As per discussion you also want to add "timestamp" along with "timetamp" at upsert right?

**Review by spolu — COMMENTED** [review]
As per discussion you also want to add "timestamp" along with "timetamp" at upsert right?

**Comment by philipperolet** [comment]
yes done

**Review by spolu — COMMENTED** [review]
The build is failing

**Review by spolu — APPROVED** [review]

**Pull request merged**
