### PR TITLE
[connectors] Recast data stored for Zendesk as BIGINT into JS numbers

### PR DESCRIPTION
**Pull request by aubin-tchoi**
## Description

- The IDs returned by Zendesk's API are too big to be stored in db as `INTEGER`s (> 2^31) but can always be represented as JS `number`s (< 2^53) as per [Zendesk's doc](https://developer.zendesk.com/api-reference/introduction/data-types/)).
- They are currently stored as `BIGINT`s, which is more practical than storing them as `VARCHAR` since we are using a [SDK](https://blakmatrix.github.io/node-zendesk/) that wraps Zendesk's API and returns them as numbers.
- This PR aims at adding validation on save and recasting these values into numbers on fetch.
- Open to suggestions regarding the approach and the implementation.

Example `brandId`: 24050113285393.

Update: we should override the type parser of Sequalize since we are going to need `BIGINT`s in other projects (sharding notably). However it does not seem to be easy, we use and outdated version and can't seem to be able to choose between `node-postgres` and `pg`. This will be handled at another time, for the moment we are going to cast in the Resource after fetching.
https://github.com/brianc/node-postgres/pull/353
https://github.com/sequelize/sequelize/issues/9074

## Risk

Low.

## Deploy Plan

- Deploy connectors.

### CODE REVIEW

**Review by flvndvd — COMMENTED** [review]
Here are my two senses:
- Most connectors with this constraint will store ids as string (e.g: Confluence) if the library allows it.
- If the library enforces the `Number` JS type (2^53 - 1), then you might want to make sure that when you save it in DB, it does not go above the `Number.MAX_SAFE_INTEGER` since PostgreSQL's `BigInt` can support bigger numbers than JS `Number` (see [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)). If this contract is respected pretty sure you don't need the parsing.

**Review by fontanierh — COMMENTED** [review]
Agreed I think these could simply be strings

**Comment by aubin-tchoi** [comment]
@fontanierh the SDK we use ([node-zendesk](https://blakmatrix.github.io/node-zendesk/)) uses numbers everywhere so it's more practical to keep numbers in our code

**Comment by aubin-tchoi** [comment]
@flvndvd I added some validation on save in the models, but still this doesn't really tell Sequalize that the values can be safely cast into numbers (in practice it doesn't, I still get strings), what that what you had in mind?

**Comment by aubin-tchoi** [comment]
PMRR

**Review by flvndvd — COMMENTED** [review]
Will make sure to change this so it applies to all BigInt types used in PostgreSQL.

**Pull request merged**
