### PR TITLE
Fix conversation actions type

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

This PR fixes the conversation actions types. `renderForFunctionCall` and `renderForMultiActionsModel` are not exposed to the public API, they are internal only methods. 

This fixes the errors observed [here](https://app.datadoghq.eu/logs?query=%22DustAPI%20error%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AwAAAZMApU-mhx1pIQAAABhBWk1BcFZFQkFBREtldDAtM2FXWUdBQW8AAAAkMDE5MzAwYTktMzY1My00YzQxLWJiOTEtODNjYzA0ZWMyMzRiAAANuA&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1730869642863&to_ts=1730884042863&live=true).

### CODE REVIEW

**Comment by Fraggle** [comment]
Weird, I had to add theses 2 to fix something.
Check in connectors & front if the typing are fine.

**Review by Fraggle — APPROVED** [review]
But double check

**Comment by flvndvd** [comment]
> Weird, I had to add theses 2 to fix something. Check in connectors & front if the typing are fine.

Do you remember what it was needed for?

**Comment by Fraggle** [comment]
> Do you remember what it was needed for?

Type check issue, if it passes the 2 tsc checks (connectors and front) then you are good.

**Comment by flvndvd** [comment]
Weird it was passing locally, but failed on the CI. Will fix.

**Pull request merged**
