### PR TITLE
Sort content nodes by title ASC

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

This PR fixes https://github.com/dust-tt/tasks/issues/1601.

It sort content nodes retrieved from connectors by title ASC to ease visual parsing in the app.

### CODE REVIEW

**Review by JulesBelveze — APPROVED** [review]
LGTM

**Review by tdraier — APPROVED** [review]

**Comment by spolu** [comment]
This will be revisited as we move to core anyway but isn't it breaking some connectors orderings (eg google drive folders first and files second?)

@philipperolet interesting question for core here. Maybe we want to have folders first maybe not maybe something more complete but I doubt it?

**Comment by flvndvd** [comment]
It does indeed, I had no idea we were applying specific sorts per connector. Will update to sort by type as well.

**Comment by philipperolet** [comment]
> This will be revisited as we move to core anyway but isn't it breaking some connectors orderings (eg google drive folders first and files second?)
> 
> @philipperolet interesting question for core here. Maybe we want to have folders first maybe not maybe something more complete but I doubt it?

Ack, folders first seems a good starting point

**Pull request merged**
