### PR TITLE
add markdown support

### PR DESCRIPTION
**Pull request by philipperolet**
This adds markdown support
@spolu FYI since AFK / post-merge

### CODE REVIEW

**Review by fontanierh — DISMISSED** [review]
LGTM, really nice, I was execting a much bigger diff 🔥

**Comment by philipperolet** [comment]
> LGTM, really nice, I was execting a much bigger diff fire

:pray: and :+1: it was actually more about picking the tool, reading the doc & making the CSS work than writing code :smile:

**Review by spolu — DISMISSED** [review]
LGTM code wise 👍

from my experience playing with react markdown and tailwind I remember having issues with humongous vertical spacing, did you run into the same issues?

Can you share a few screenshots? 🙏

**Comment by philipperolet** [comment]
I did run into those; had to tweak the css. Here are some screenshots
image
image

**Comment by philipperolet** [comment]
image

**Pull request merged**
