### PR TITLE
Sparkle effects

### PR DESCRIPTION
**Pull request by Duncid**
## Description
Sparkle Effect

## Risk
n/a

### CODE REVIEW

**Comment by Duncid** [comment]
@philipperolet not sure why there are multiple package-lock changes like that.
Normally, changes should be contained now in just tailwind config and new files.

**Comment by philipperolet** [comment]
Will have a look first thing Tuesday

**Comment by Duncid** [comment]
Gentle ping @philipperolet ^^'

**Comment by philipperolet** [comment]
:wave: Hey
Fixed your issue. The changes you made let the rainbow show a little by transparency in the div, is that intentional?

**Review by philipperolet — COMMENTED** [review]
:wave: Thanks, left a com

**Comment by Duncid** [comment]
> 👋 Hey
> Fixed your issue.

Thanks so much, I'm very curious, what did I do wrong?

> The changes you made let the rainbow show a little by transparency in the div, is that intentional?

Yes

**Comment by philipperolet** [comment]
The tailwind config was malformed, probably a copy paste issue

**Pull request merged**
