### PR TITLE
Updating package version

### PR DESCRIPTION
**Pull request by Duncid**

### CODE REVIEW

**Comment by Duncid** [comment]
> This won't build because Sparkle is not yet published. Has to be made in 2 steps :)

Actually, you can run the sparkle deploy action from a branch.
So I make the branch, make changes both in front and sparkle, push, deploy from branch then test works :)

**Comment by PopDaph** [comment]
It has broken the deploy tho 😅 
https://github.com/dust-tt/dust/actions/runs/6037635917/job/16382290825

**Comment by Duncid** [comment]
Shit…
From what I understand it's not running the npm install after deploying the new sparkle package that broke it right?

**Comment by PopDaph** [comment]
No worries, fix is here: https://github.com/dust-tt/dust/pull/1211 and I deployed again!

When you bump the version of sparkle on `front/package.json`, you also have to run `npm install` on front so that `front/package-lock.json`  is updated accordingly 🙏🏻

**Pull request merged**
