### PR TITLE
fix: don't fail upsert if doc is empty

### PR DESCRIPTION
**Pull request by fontanierh**

### CODE REVIEW

**Review by lasryaric — APPROVED** [review]
I am fine with this diff as long as we are sure it makes sense to not fail on empty docs.
What is the point of upserting an empty doc?

**Comment by fontanierh** [comment]
> What is the point of upserting an empty doc?

If it was previously non-empty, we probably need to remove the content. 
I'm wondering what is best between having the empty doc or simply deleting the doc.

**Comment by lasryaric** [comment]
> 

Good point. I did not think of the "deleting the doc" case. I honestly don't have a strong opinion. Maybe @spolu ?

**Review by spolu — APPROVED** [review]
LGTM

**Comment by spolu** [comment]
As per IRL this is related to a "really empty" document.

I think it makes sense to have this here.

We could do the following:
- Add a guard in the API endpoint against empty documents
- Do not attempt to upsert when a document is empty in the connector

But that means that if a document was not empty and becomes empty we won't reflect the true state. So I think this is the correct state of affair.

**Pull request merged**
