### PR TITLE
Changing pricing page and adding request demo button

### PR DESCRIPTION
**Pull request by thib-martin**
## Description

Goal is to simplify "access to demo" on our website and better show difference between plans on our pricing page.

### Pricing Page
image

### Request Demo Button on top menu (links to the intro call form)
image

## Risk
* overloading ourselves with non-qualified leads (e.g. pro plans) ?

### CODE REVIEW

**Comment by thib-martin** [comment]
@Adugre @clmrn @nchinot @ahammour what do you think about the following proposals?

Happy to change wording, etc. This is a V0 to show what's possible.

**Comment by clmrn** [comment]
@thib-martin looks neat! 

A few comments: 
- 'restricted spaces' is not self-explanatory IMO 
- Single Sign On (Okta, Entra ID, Jumpcloud) 
- '(soon) Salesforce connector' in Enterprise

**Comment by nchinot** [comment]
Aligned with @clmrn , thanks for taking the lead on this.

**Comment by thib-martin** [comment]
Thanks for the feedback. Here's an updated view, does this look better to you?

Note: we'll probably iterate on the contact form (moving to typeform or a hubspot form) but 'growth hacking' is not the top priority for now.

image

@gabhubert @spolu ok with this?

**Comment by spolu** [comment]
LGTM 👍

**Comment by gabhubert** [comment]
- What's the wording on a US IP? WE should also sell "US data hosting" in the US. 
- I don't think we need the "soon" for data hosting given our time to close deals

**Review by JulesBelveze — APPROVED** [review]
LGTM

**Pull request merged**
