### PR TITLE
Attempt to silent npm run

### PR DESCRIPTION
**Pull request by PopDaph**
🤞🏻

### CODE REVIEW

**Review by spolu — APPROVED** [review]
To test on edge ;-)

**Comment by PopDaph** [comment]
Yes that's exactly how I discovered edge was broken 😅

**Comment by PopDaph** [comment]
Front edge seems to work > I was able to create a convo.
I'm guessing everything would have been broken if config was not right. I'm not sure this will properly silent the logs we want to get rid of but at least it does not seem harmful.

**Comment by PopDaph** [comment]
It did not work 😭 
Screenshot 2023-11-23 at 12 17 06

**Comment by spolu** [comment]
glups

**Pull request merged**
