### PR TITLE
Sparkle citation img

### PR DESCRIPTION
**Pull request by Duncid**
## Description

Adapting Citation for Images

### CODE REVIEW

**Comment by flvndvd** [comment]
Don't we want to push this all the way @Duncid?

**Comment by Duncid** [comment]
I thought you had integrated in your project.
What's left to do? Merge?

Don't remember if it's breaking or not.

**Comment by flvndvd** [comment]
Yep merging, will take it over.

**Comment by Duncid** [comment]
@flvndvd I don't think it's breaking. If you approve I'll merge.

**Review by flvndvd — APPROVED** [review]
LGTM

**Pull request merged**
