### PR TITLE
[Ahuna] Views for getAgentConfigurations 

### PR DESCRIPTION
**Pull request by philipperolet**
Fixes #2808 and previously #2778 

- Fixes failing calls to getAgentConfigurations when user was not set 
- Default to view "all" for api get calls without a "view" parameter

Related [discussion](https://dust4ai.slack.com/archives/C050SM8NSPK/p1702039668546789)

### CODE REVIEW

**Review by spolu — APPROVED** [review]
LGTM

lets make sure to test on front-edge first 👍

**Comment by philipperolet** [comment]
Thx for taking time to review. Confirmong it has been tested on front edge (it is currently deployed there). Will merge this afternoon before 4p at latest

**Comment by spolu** [comment]
ack :+1:

**Comment by philipperolet** [comment]
Ultimate query explain in prod
```
EXPLAIN ANALYZE SELECT "agent_configuration"."id", "agent_configuration"."createdAt", "agent_configuration"."updatedAt", "agent_configuration"."sId", "agent_configuration"."version", "agent_configuration"."status", "agent_configuration"."scope", "agent_configuration"."name", "agent_configuration"."description", "agent_configuration"."pictureUrl", "agent_configuration"."workspaceId", "agent_configuration"."generationConfigurationId", "agent_configuration"."retrievalConfigurationId","agent_configuration"."dustAppRunConfigurationId", "agent_configuration"."authorId", "generationConfiguration"."id" AS "generationConfiguration.id", "generationConfiguration"."createdAt" AS "generationConfiguration.createdAt", "generationConfiguration"."updatedAt" AS "generationConfiguration.updatedAt", "generationConfiguration"."prompt" AS "generationConfiguration.prompt", "generationConfiguration"."providerId" AS "generationConfiguration.providerId", "generationConfiguration"."modelId" AS "generationConfiguration.modelId", "generationConfiguration"."temperature" AS "generationConfiguration.temperature", "retrievalConfiguration"."id" AS "retrievalConfiguration.id", "retrievalConfiguration"."createdAt" AS "retrievalConfiguration.createdAt", "retrievalConfiguration"."updatedAt" AS "retrievalConfiguration.updatedAt", "retrievalConfiguration"."sId" AS "retrievalConfiguration.sId", "retrievalConfiguration"."query" AS "retrievalConfiguration.query", "retrievalConfiguration"."queryTemplate" AS "retrievalConfiguration.queryTemplate", "retrievalConfiguration"."relativeTimeFrame" AS "retrievalConfiguration.relativeTimeFrame", "retrievalConfiguration"."relativeTimeFrameDuration" AS "retrievalConfiguration.relativeTimeFrameDuration", "retrievalConfiguration"."relativeTimeFrameUnit" AS "retrievalConfiguration.relativeTimeFrameUnit", "retrievalConfiguration"."topK" AS "retrievalConfiguration.topK", "retrievalConfiguration"."topKMode" AS "retrievalConfiguration.topKMode", "dustAppRunConfiguration"."id" AS "dustAppRunConfiguration.id", "dustAppRunConfiguration"."createdAt" AS "dustAppRunConfiguration.createdAt", "dustAppRunConfiguration"."updatedAt" AS "dustAppRunConfiguration.updatedAt", "dustAppRunConfiguration"."sId" AS "dustAppRunConfiguration.sId", "dustAppRunConfiguration"."appWorkspaceId" AS "dustAppRunConfiguration.appWorkspaceId", "dustAppRunConfiguration"."appId" AS "dustAppRunConfiguration.appId", "agent_user_relations"."id" AS "agent_user_relations.id", "agent_user_relations"."relation" AS "agent_user_relations.relation" FROM "agent_configurations" AS "agent_configuration" LEFT OUTER JOIN "agent_generation_configurations" AS "generationConfiguration" ON "agent_configuration"."generationConfigurationId" = "generationConfiguration"."id" LEFT OUTER JOIN "agent_retrieval_configurations" AS "retrievalConfiguration" ON "agent_configuration"."retrievalConfigurationId" = "retrievalConfiguration"."id" LEFT OUTER JOIN "agent_dust_app_run_configurations" AS "dustAppRunConfiguration" ON "agent_configuration"."dustAppRunConfigurationId" = "dustAppRunConfiguration"."id" LEFT OUTER JOIN "agent_user_relations" AS "agent_user_relations" ON "agent_configuration"."id" = "agent_user_relations"."agentConfigurationId" AND "agent_user_relations"."userId" = 1 WHERE ("agent_configuration"."scope" IN ('published', 'workspace') OR "agent_configuration"."authorId" = 1) AND "agent_configuration"."workspaceId" = 4525 AND "agent_configuration"."status" = 'active';
                                                                                                     QUERY PLAN                                                                                                     
 
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-
 Nested Loop Left Join  (cost=209.88..962.19 rows=126 width=3017) (actual time=0.593..2.628 rows=62 loops=1)
   Join Filter: (agent_configuration.id = agent_user_relations."agentConfigurationId")
   ->  Hash Left Join  (cost=209.73..951.09 rows=126 width=2497) (actual time=0.585..2.571 rows=62 loops=1)
         Hash Cond: (agent_configuration."dustAppRunConfigurationId" = "dustAppRunConfiguration".id)
         ->  Nested Loop Left Join  (cost=205.28..946.31 rows=126 width=929) (actual time=0.512..2.461 rows=62 loops=1)
               ->  Hash Right Join  (cost=205.00..324.50 rows=126 width=283) (actual time=0.502..2.011 rows=62 loops=1)
                     Hash Cond: ("retrievalConfiguration".id = agent_configuration."retrievalConfigurationId")
                     ->  Seq Scan on agent_retrieval_configurations "retrievalConfiguration"  (cost=0.00..102.27 rows=3327 width=91) (actual time=0.209..1.435 rows=3501 loops=1)
                     ->  Hash  (cost=203.42..203.42 rows=126 width=192) (actual time=0.245..0.246 rows=62 loops=1)
                           Buckets: 1024  Batches: 1  Memory Usage: 22kB
                           ->  Bitmap Heap Scan on agent_configurations agent_configuration  (cost=5.57..203.42 rows=126 width=192) (actual time=0.055..0.198 rows=62 loops=1)
                                 Recheck Cond: (("workspaceId" = 4525) AND ((status)::text = 'active'::text))
                                 Filter: (((scope)::text = ANY ('{published,workspace}'::text[])) OR ("authorId" = 1))
                                 Heap Blocks: exact=50
                                 ->  Bitmap Index Scan on agent_configurations_workspace_id_status_name  (cost=0.00..5.54 rows=126 width=0) (actual time=0.041..0.041 rows=82 loops=1)
                                       Index Cond: (("workspaceId" = 4525) AND ((status)::text = 'active'::text))
               ->  Index Scan using agent_generation_configurations_pkey on agent_generation_configurations "generationConfiguration"  (cost=0.28..4.93 rows=1 width=646) (actual time=0.006..0.006 rows=1 loops=62)
                     Index Cond: (id = agent_configuration."generationConfigurationId")
         ->  Hash  (cost=3.09..3.09 rows=109 width=1568) (actual time=0.047..0.048 rows=146 loops=1)
               Buckets: 1024  Batches: 1  Memory Usage: 21kB
               ->  Seq Scan on agent_dust_app_run_configurations "dustAppRunConfiguration"  (cost=0.00..3.09 rows=109 width=1568) (actual time=0.007..0.019 rows=146 loops=1)
   ->  Materialize  (cost=0.14..9.21 rows=1 width=524) (actual time=0.000..0.000 rows=0 loops=62)
         ->  Index Scan using agent_user_relation_config_workspace_user_idx on agent_user_relations  (cost=0.14..9.21 rows=1 width=524) (actual time=0.005..0.005 rows=0 loops=1)
               Index Cond: ("userId" = 1)
 Planning Time: 2.742 ms
 Execution Time: 2.963 ms
                                                                                                                    
```

**Pull request merged**
