### PR TITLE
Allow notifications to be hoverable / closeable on modals

### PR DESCRIPTION
**Pull request by philipperolet**
Also moves them to the bottom
Related [discussion](https://dust4ai.slack.com/archives/C050SM8NSPK/p1697714565463949) with context and screenshots

### CODE REVIEW

**Review by fontanierh — APPROVED** [review]
Looks good, does it work properly if the page is server side rendered?
Assuming this doesnt break autoscroll 😆

**Comment by philipperolet** [comment]
> Assuming this doesnt break autoscroll 😆
Lol same joke at the same time :)

**Comment by philipperolet** [comment]
> Looks good, does it work properly if the page is server side rendered?

Yes afaict when the page is SSRd react still makes a pass (setup JS events, hooks, and run all js code)
However this raises a good point => isolating the portal in NotificationList to be sure react does not re-render what isn't needed

**Comment by philipperolet** [comment]
Actually AFAICT react will only rerender the notificationlist in this case so no real need to change

**Pull request merged**
