### PR TITLE
Fix autoscroll in various situations (retrieval actions, citations...)

### PR DESCRIPTION
**Pull request by philipperolet**
Autoscroll is performed when a message is generating and the page is already scrolled down; but if the user has scrolled the page up after the start of the message, we do not want to scroll it back down. 

Checking the conversation is already at the bottom of the screen is done modulo a small margin (50px). This value is small because if large, it prevents user from scrolling up when the message continues generating (forces it back down), but it cannot be zero otherwise the scroll does not happen.

This PR fixes a few issues with the previous version, namely:
- it did not listen to some new content events (e.g. actions, citations) and thus did not scroll in this case;
- it did not scroll if the newly generated content was larger than 50px (e.g. citations);

The former is fixed via useeffect dependencies.

The latter is ensured by keeping a ref on the message's height, and accounting to the height difference when new parts of the message are generated.

### CODE REVIEW

**Comment by philipperolet** [comment]
**Technical Note**
I investigated using transitions and transitioning the height of new content from 0 to their actual height. It was appealing because it would in addition make for a nicer content display (smooth rather than blunt), but:
- fixing an autoscroll issue with transitions seemed brittle;
- there were situations in which I could not make it work;
- transitioning on the height had various implications on children of the transitions that made it IMHO bad code style;

But
- this can be revisited, TBD
- It might still be worth using transitions when content appears, independently on the scroll

**Comment by spolu** [comment]
Wait, don’t we want to scroll on new messages? Even if the user is scrolled up?

**Comment by philipperolet** [comment]
Yes, this we still do, this is done in conversation

**Review by fontanierh — APPROVED** [review]
🔥  makes a lot of sense 🙏

**Comment by philipperolet** [comment]
Seems there is still an issue on mobile, when there are citations. Will investigate when I get back

**Pull request merged**
