### PR TITLE
[Sparkle] Version bump

### PR DESCRIPTION
**Pull request by philipperolet**
## Description
Following #4502 that missed version bump

### CODE REVIEW

**Comment by philipperolet** [comment]
PMRW

**Comment by spolu** [comment]
@lasryaric as per chat yesterday let's make sure to papertrail PMRW :pray:

**Comment by philipperolet** [comment]
Mea culpa: I forgot to ping on slack  (+ the previous one assigned to @lasryaric was swiftly checked) so IMHO it was just a matter of time until approval from @lasryaric

**Comment by lasryaric** [comment]
> @lasryaric as per chat yesterday let's make sure to papertrail PMRW 🙏

Ahah for sure but lets give a little time to do it because I just did reviewed another PMRW and did not get enough time to see this one.

**Pull request merged**
