### PR TITLE
[resolver] - feat: introduce region resolver

### PR DESCRIPTION
**Pull request by JulesBelveze**
## Description

This PR aims at introducing a "resolver" service that will be used to redirect users to the right region at login.

Note: this is an initial draft to enable @Fraggle to iterate over it. It might needs some tweaking to stitch all components together and the region selection page needs to be implemented once design is ready.

## Risk

N/A

## Deploy Plan

None

### CODE REVIEW

**Review by Fraggle — APPROVED** [review]
Looks reasonnable :)

**Review by spolu — COMMENTED** [review]
We def don't need next here do we? Can we use a lower level server API similar to connectors?

**Comment by Fraggle** [comment]
> We def don't need next here do we?

We wanted to re-use something already in our stack...

> Can we use a lower level server API similar to connectors?

...but we weren't aware / realized that we used something different for connectors.

@JulesBelveze I'll let you decide what to do from here.

**Comment by JulesBelveze** [comment]
Well currently the page we render is very simple (we are waiting for the design to start implementing it), but we will probably want to use some sparkle components in there. To me using `next` here seems kinda relevant, no? Not sure we want to introduce a new framework here

**Comment by spolu** [comment]
As per IRL your call :+1: 

Alternatives are to have the "page" live in each region (whatever the region) and only has 1 API call in that cloud run. Added benefit is the simplicity of the cloud run.

The benefit of having the page here is that regions don't have to know each other which is nice.

**Comment by JulesBelveze** [comment]
Leaving as is to leverage the clusters isolation aspect. Happy to revisit later if needed 🙏🏼

**Pull request merged**
