### PR TITLE
fix: cleanup notion pages in DB when deleting the connector

### PR DESCRIPTION
**Pull request by fontanierh**
need to test it

### CODE REVIEW

**Review by spolu — APPROVED** [review]
Looks super reasonable :+1:

**Comment by spolu** [comment]
Feel free to merge once tested :+1:

**Comment by spolu** [comment]
cc @lasryaric we probably want to remove the slack configuration object here to avoid it being dangling

**Comment by fontanierh** [comment]
does the trick 👍  merging

**Pull request merged**
