### PR TITLE
Better UI for datasource tags in Dust Apps

### PR DESCRIPTION
**Pull request by albandum**
## Description

Better UI for datasource tags in Dust Apps
Screenshot 2024-07-10 at 14 14 39

### CODE REVIEW

**Review by flvndvd — APPROVED** [review]

**Comment by spolu** [comment]
Minor ask

@albandum 

Can we align the design and code with the way stop words are implemented in the Chat block 🙏

**Comment by spolu** [comment]
Main difference is on the precense of the cross and borders on hover

**Comment by spolu** [comment]
Also note that the cross it we keep it should be an icon not a character 🙏

**Comment by flvndvd** [comment]
> Also note that the cross it we keep it should be an icon not a character 🙏

This was mainly to unblock us, we talked about polishing this UI a bit more as we start shedding more light on it.

**Comment by albandum** [comment]
Yeah that was really a hotfix to let doctolib use this part of the dust apps - can definitely revamp in a cleaner way !

**Comment by albandum** [comment]
I'd advocate to keep the cross (can switch it to icon for sure) as it's quite standard for tags if they're not staying inside of the text input

**Comment by spolu** [comment]
Sure but let's use an icon and not `x` :) :+1: 

Agreed on the hotfixes of course but it's equal amount of work to cargo-cult the existing code vs creating disparity of UI :+1: 

Not obvious to know the same thing exist already of course. I should have jumped in earlier :+1:

**Comment by albandum** [comment]
-> https://github.com/dust-tt/dust/pull/6176

**Pull request merged**
