### PR TITLE
Package all site under `front/pages/site/`

### PR DESCRIPTION
**Pull request by spolu**
## Description

Move all pages and components below `front/site` so that all of our website code is packaged in one coherent place.

## Risk

Low if build passes

## Deploy Plan

- deploy `front`

r? @fontanierh cc @Duncid

### CODE REVIEW

**Review by fontanierh — COMMENTED** [review]
Isn't it a bit weird to have `/components` under `pages` ? Stuff in pages should be nextjs routes

**Comment by spolu** [comment]
It's is but it's so much better to have everything together under one directory no?

**Comment by fontanierh** [comment]
@spolu then why not put everything in `/components/site` and have the files in `/pages` just import/export ?

**Comment by fontanierh** [comment]
That way we basically never edit the stuff in `/pages/site` unless we have to change get server side props ?

**Comment by spolu** [comment]
Created a middleware to redirect to a 404 when hitting the components URLs

**Review by fontanierh — APPROVED** [review]
🫣

**Pull request merged**
