### PR TITLE
[Slack connector deletion] Skip app uninstall if nango conn. unknown

### PR DESCRIPTION
**Pull request by philipperolet**
## Description
It can happen that when we delete a slack datasource, the nango connection does not exist anymore 

Previously, this  resulted in an error when trying to uninstall the slack app, cancelling the slack datasource deletion, and if done via stripe webhooks (e.g. for a downgrade) triggered monitors indefinitely, since stripe retries webhooks

This PR handles the issue by skipping the app uninstall if the nango connection is unknown--we then complete the datasource deletion

Related [discussion](https://dust4ai.slack.com/archives/C05F84CFP0E/p1706008431775259?thread_ts=1706007633.055059&cid=C05F84CFP0E)

## Risk
- On the PR, risk was mitigated by testing on connectors edge on the actual workspace & slack connection that triggered the error in the above discussion
- In general, TBD whether we want to warn the user so they ensure the app is uninstalled

### CODE REVIEW

**Review by spolu — CHANGES_REQUESTED** [review]
I think we should instead make it a ExternalOauthTokenError which is our errors. We’re likely missing a condition/error code where that error is constructed. 

From there we’ll have the right code path in place here already

**Comment by spolu** [comment]
@philipperolet I presume adding the error code here: https://github.com/dust-tt/dust/blob/main/connectors/src/connectors/slack/lib/slack_client.ts#L89

is what we want?

**Comment by philipperolet** [comment]
> @philipperolet I presume adding the error code here: https://github.com/dust-tt/dust/blob/main/connectors/src/connectors/slack/lib/slack_client.ts#L89
> 
> is what we want?
We can't do that because it's not a Slack error; the error precedes getting the slack client, it's when getting the token from nango

The error has a different format, AxiosError. We also should exit before trying to delete the nango connection since the issue is we don't have the nango connection, so it's not exactly the same flow

IMHO it's fine like this, but open to discuss and change any other way ofc

**Comment by philipperolet** [comment]
I can make clearer that the error comes from `getSlackAccessToken` by putting it in a prior separate try/catch block?

**Review by spolu — APPROVED** [review]
LGTM

Would be in favor of moving the logic of extracting the Axios error in the nango function and throw a typed NangoOAuthTokenError on which you can act here (but we will also be able to act in the future)

**Review by spolu — APPROVED** [review]

**Pull request merged**
