### PR TITLE
Upload at most 4 files at the time

### PR DESCRIPTION
**Pull request by Fraggle**
## Description

Avoid too much delay between file creation and file upload, leading to errors.

I think it's the cause of [these](https://app.datadoghq.eu/logs?query=%20@apiError.api_error.message:%22File%20upload%20has%20expired.%20Create%20a%20new%20file.%22&agg_m=count&agg_m_source=base&agg_t=count&cols=host,service&fromUser=true&link_source=monitor_notif&messageDisplay=inline&storage=hot&stream_sort=desc&viz=stream&from_ts=1732749158198&to_ts=1734045158198&live=true).

## Risk

Low, tested locally.

## Deploy Plan

Deploy `front`

### CODE REVIEW

**Review by spolu — COMMENTED** [review]
Ideally we want to use concurrentExecutor 

We're trying to get rid of pqueue as a dependency 👍

**Comment by fontanierh** [comment]
> We're trying to get rid of pqueue as a dependency 👍

@spolu why did we go with this decision ? Concurrent executor is inferior to pqueue since it naively goes through the elements batch by batch, instead of keeping concurrency constant throughout the processing

**Review by spolu — APPROVED** [review]

**Comment by spolu** [comment]
@fontanierh pqueue really is finicky with error handling. We can easily improve concurrentExecutor while keeping a good understanding of its error handling which I think is nice :+1: @flvndvd had other take on pqueue but I don't rememember what it was?

**Comment by Fraggle** [comment]
I confirm that it does not do batch by batch (I checked before pushing via network debug).

**Comment by fontanierh** [comment]
> @fontanierh pqueue really is finicky with error handling. We can easily improve concurrentExecutor while keeping a good understanding of its error handling which I think is nice 👍 @flvndvd had other take on pqueue but I don't rememember what it was?

pqueue isn't finicky, it's a matter of understanding how it works. Our concurrentExecutor in `connectors` uses pQueue under the hood


> @flvndvd had other take on pqueue but I don't rememember what it was?

Something about esmodules which makes it not possible to have pqueue in front I think

> Note: concurrentExecutor does not go batch by batch based on what I'm reading of its code.

nvm that's outdated info 👍 Looks like the latest iteration of `concurrentExecutor` in types is not batch by batch so sounds good to me 👍

**Pull request merged**
