### PR TITLE
[Conversation UX] When copying mention, don't copy assisant description

### LINKED ISSUE #5699: Do not paste assistant description when pasting message
When copying text with an assistant mention, the assitant's description is copied, which should be avoided. See https://github.com/dust-tt/tasks/issues/882

### PR DESCRIPTION
**Pull request by philipperolet**
Description
---

Fixes https://github.com/dust-tt/dust/issues/5699 and relatedly https://github.com/dust-tt/tasks/issues/882

Before:
Screencast from 2024-06-26 15-20-16

After:
Screencast from 2024-06-26 15-22-50

Risk & deploy
---
na

### CODE REVIEW

**Review by PopDaph — COMMENTED** [review]
This kinda looks like a hack with a setTimeout to get rid of a weird behavior from our Tooltip component, shouldn't we fix the component instead?  

Everywhere we use a tooltip we potentially have this problem.
(Sorry 🙈 )

**Comment by philipperolet** [comment]
Good point; will try to make it work at the tooltip component level 
(not sure I can avoid the setTimeout though; can try, but will limit investigation since i'm already 2 hours+ in this rather mild but surprisingly challenging issue)

**Comment by philipperolet** [comment]
Actually, the little issue I'd see with this is that sometimes you may want to select the tooltip text...

**Comment by PopDaph** [comment]
> Actually, the little issue I'd see with this is that sometimes you may want to select the tooltip text...

I just discussed it with @Duncid and he confirms we don't want to allow selecting the tooltip texts, tooltips content are not meant to be copy/pasted 🙏🏻

**Comment by philipperolet** [comment]
closing, moved to https://github.com/dust-tt/dust/pull/5890

**Comment by philipperolet** [comment]
Reopening. Doing this at the tooltip level does not work unfortunately

This is because onCopy events are only sent to the largest enclosing element; so the tooltip only receives them if you only select the content it tooltips, which defeats the point here

I think I have to timebox it now, so would like to fix the original issue with this if ok with you?

**Comment by philipperolet** [comment]
After irl discussion, we'll just remove the tooltip on the mentions cc @Duncid

**Comment by philipperolet** [comment]
closed in favor of https://github.com/dust-tt/dust/pull/5892

**Pull request closed without merging**
