### PR TITLE
Flav/refactor slack bot post conversation url

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

This PR restructures the Slack bot code, which had become overly large and redundant in many areas.

Key changes include:
- Adopting Slack's blocks for enhanced flexibility and better-structured messages (we still post the plain text in case the blocks are not rendering e.g: push notifications).
- Posting the conversation URL earlier in the event of timeouts or other downstream errors.

image

SlackPostMessage

## Risk

Tested the workflow E2E locally!

### CODE REVIEW

**Review by spolu — APPROVED** [review]
Looks very reasonable.

Does it fix tropePrep?? 😬

**Comment by flvndvd** [comment]
> Looks very reasonable.
> 
> Does it fix tropePrep?? 😬

The fix is coming in another PR, the issue is with our markdown library ([example](https://app.datadoghq.eu/logs?query=%22Unexpected%20exception%20answering%20to%20Slack%20Chat%20Bot%20message%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZAndbmc-662hgAAAAAAAAAYAAAAAEFaQW5kY2tMQUFCTjdxU1VZdXVxZ1FBVwAAACQAAAAAMDE5MDI3N2QtYTczZS00N2E2LWE4MGItZjg0YmZiMDE2YmE4&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718637645151&to_ts=1718652045151&live=true))

**Comment by flvndvd** [comment]
> > Looks very reasonable.
> > Does it fix tropePrep?? 😬
> 
> The fix is coming in another PR, the issue is with our markdown library ([example](https://app.datadoghq.eu/logs?query=%22Unexpected%20exception%20answering%20to%20Slack%20Chat%20Bot%20message%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZAndbmc-662hgAAAAAAAAAYAAAAAEFaQW5kY2tMQUFCTjdxU1VZdXVxZ1FBVwAAACQAAAAAMDE5MDI3N2QtYTczZS00N2E2LWE4MGItZjg0YmZiMDE2YmE4&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718637645151&to_ts=1718652045151&live=true))

Here you go: https://app.datadoghq.eu/logs?query=%22Unexpected%20exception%20answering%20to%20Slack%20Chat%20Bot%20message%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZAndbmc-662hgAAAAAAAAAYAAAAAEFaQW5kY2tMQUFCTjdxU1VZdXVxZ1FBVwAAACQAAAAAMDE5MDI3N2QtYTczZS00N2E2LWE4MGItZjg0YmZiMDE2YmE4&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718637645151&to_ts=1718652045151&live=true.

**Comment by flvndvd** [comment]
> > Looks very reasonable.
> > Does it fix tropePrep?? 😬
> 
> The fix is coming in another PR, the issue is with our markdown library ([example](https://app.datadoghq.eu/logs?query=%22Unexpected%20exception%20answering%20to%20Slack%20Chat%20Bot%20message%22%20&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAZAndbmc-662hgAAAAAAAAAYAAAAAEFaQW5kY2tMQUFCTjdxU1VZdXVxZ1FBVwAAACQAAAAAMDE5MDI3N2QtYTczZS00N2E2LWE4MGItZjg0YmZiMDE2YmE4&fromUser=true&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1718637645151&to_ts=1718652045151&live=true))

Here you go: https://github.com/dust-tt/dust/pull/5693.

**Comment by lasryaric** [comment]
Thank you @flvndvd

**Pull request merged**
