### PR TITLE
Flav/instructions characters count

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

We observed that some assistants have overly lengthy instructions. This PR introduces a character limit for instructions. With this update, editing existing instructions that exceed this limit will be restricted until the content is reduced to an acceptable size.

To avoid exposing the limit we will only start displaying the character count when we reach half of the limit.

instructionsCharactersCount

## Risk

Made sure to test the case of loading existing assistants with instructions that exceeds the limit.

### CODE REVIEW

**Comment by philipperolet** [comment]
Weird, we already had a limit!

**Review by philipperolet — COMMENTED** [review]
Can you explain in PR how it differs from https://github.com/dust-tt/dust/pull/5099 from a month ago?

**Comment by flvndvd** [comment]
This PR is visual, and your limit is 1_000_000, this one here is 100_000 🙃. I won't update the BE for now, until we reached out to the customers impacted.

**Comment by flvndvd** [comment]
PR and description updated @philipperolet (good catch 🙏).

**Review by philipperolet — APPROVED** [review]
Neat :nail_care:

**Pull request merged**
