### PR TITLE
[Runner] Replace role "user" by "member"

### PR DESCRIPTION
**Pull request by philipperolet**
Related [task](https://github.com/dust-tt/tasks/issues/281)

Migration plan:
- deploy front -- 'user' value is still supported
- `init_db` in front
- migration
- remove 'user' value and role getter from Model
- deploy front
- `init_db` again

### CODE REVIEW

**Comment by spolu** [comment]
Wait what? no? Why?

Let's make the change a purely front-end change please :pray: :)

**Review by spolu — COMMENTED** [review]
Wait what? no? Why?

Let's make the change a purely front-end change if needed, but let's not change our internal role naming here :pray:

**Review by spolu — CHANGES_REQUESTED** [review]
Let's just change the members page visual please. This is too risky. And may change for another terminology in weeks.

**Comment by philipperolet** [comment]
hmm why not align namings? I don't think it's that risky, I tested it locally including the migration

The more we add translations between product speak and code speak the harder it gets for us. When there's good reason because the concepts don't match, then I would agree, but here they match perfectly. I personally feel Agent/Assistant is a bit painful already

When you say it's too risky and terminology might change, the right answer IMHO is to make it less risky and easier to change. We can make the name easier to change for sure, a lot of arrays in the code should have come from an  exported role array and RoleType should be derived from it

But ideally, terminology change product side should be harder and we should be more reluctant to do it than code side, because of the friction it causes to users, need for coms, etc. Code should be remain easier to change than people's habbits. So this kind of change shouldn't happen that much.

Glad to discuss if you disagree

**Comment by philipperolet** [comment]
I realize I wrote a lot about this non-critical topic :sweat_smile: Because I actually pondered doing the quick & easy front-end change and decided to go for the longer more involved full renaming because I thought it would make things simpler for us in the future

**Comment by spolu** [comment]
> hmm why not align namings?

Basically because front-end names change all the time :)

**Comment by philipperolet** [comment]
> But ideally, terminology change product side should be harder and we should be more reluctant to do it than code side, because of the friction it causes to users, need for coms, etc. Code should be remain easier to change than people's habbits. So this kind of change shouldn't happen that much.

This is why I believe frontend names will change less over time. Cf also the rest explaining my point of view => but ok to D&C

Furthermore, the part of me that wants less work and less risks before Xmas actually agrees => will change

**Comment by philipperolet** [comment]
Closing, follow up PR #2983

**Pull request closed without merging**
