### PR TITLE
add UI changes/simplifying gens

### PR DESCRIPTION
**Pull request by Uzay-G**

### CODE REVIEW

**Comment by Uzay-G** [comment]
Adds:

- clipboard button
- How does Gens work? panel
- data source placement stuff
- other fixes

**Comment by Uzay-G** [comment]
I still need to fix the data source UI stuff, after those conflicts. Note: @spolu, what contexts do you use topK in? If we keep that we need to make it more legible.

Currently it looks like this, can bring the data sources / other search stuff back down depending on what you think @spolu

**Comment by spolu** [comment]
I use it to go deeper then select documents and then clear to focus on one document type I can recognize and know I want to use for a specific tempalte

**Comment by spolu** [comment]
I would suggest the following:

- keep the current layout for data sources / time range and topk (1 by line) but have all that hidden behind an "Settings" collapse?
- How does gen work can be on the right at the same level of the templates?
- The copy button can probably be a bit smaller, does it react when you click on it? does it have a cursor pointer? Is there a hover style?

**Comment by spolu** [comment]
Screenshot from 2023-07-13 12-45-16

Some idea for Advanced

**Comment by Uzay-G** [comment]
> The copy button can probably be a bit smaller, does it react when you click on it? does it have a cursor pointer? Is there a hover style?

Ok/no/yes/yes

> keep the current layout for data sources / time range and topk (1 by line) but have all that hidden behind an "Settings" collapse?
Ok, maybe i'll move those changes to another PR

**Comment by spolu** [comment]
The copy button should turn into a copy with checkmark (I think it exists in heroicons) or a checkmark alone once clicked and revert back after 1-2s :+1:

**Comment by spolu** [comment]
(Since, if there is no feedback there's no way for the user to know if something happened)

**Comment by Uzay-G** [comment]
Okay, I was wondering what to do about that, perfect.

**Comment by Uzay-G** [comment]
random

**Comment by spolu** [comment]
Looks OK. Please preserve TopK. 
Let's not make the "Learn more about Gens" a button it's confusing should be text IMHO or at least not an ActionButton but a Button. Otherwise feels like a top-level action of the app.

**Comment by Uzay-G** [comment]
image

**Comment by Uzay-G** [comment]
the strong border on the how does gens work button is just because it was clicked when I had the screenshot.

**Review by spolu — APPROVED** [review]

**Pull request merged**
