### PR TITLE
Testing Adobe Font

### PR DESCRIPTION
**Pull request by Duncid**
This PR sets the "Darkmode" font as default font.
It works on storybook, no idea if it works anywhere else.

The adobe font package is loaded using import (@import url("https://use.typekit.net/jnb2umy.css").
It could be loaded the the head of the html:

```
<style>
  @import url("https://use.typekit.net/jnb2umy.css");
</style>
```

### CODE REVIEW

**Comment by spolu** [comment]
We can test that together on a call as I guess we need to go around the product to see how breaking that would be?

**Review by spolu — APPROVED** [review]
LGTM

Tested in front and moving front as well there in another PR

**Comment by spolu** [comment]
cc @fontanierh I think we're good the font is only imported for the storybook css but not the other.

**Comment by spolu** [comment]
It had a fairly big impact on Linux leading to a meh meh visual of the app.

I saw that @Duncid went with another one for the updated landing (which looks great!) so probably worth an additional discussion?

Out of curiosity did you try this one on Mac for front ?

**Comment by fontanierh** [comment]
I did @spolu

Prod:
Screenshot 2023-08-02 at 15 09 02

With the other font:
Screenshot 2023-08-02 at 15 09 24

**Comment by fontanierh** [comment]
Let's be real, I hardly see any difference but I am not a designer

**Comment by spolu** [comment]
So I think the updated landing changed the app fonts altogether. See: https://github.com/dust-tt/dust/blob/main/front/tailwind.config.js#L11

We'll need to dig into how to handle the multiple font families we'll need.

**Pull request closed without merging**
