### PR TITLE
Use proper image prefix when building

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

This PR resolves an issue where the same prefix was used across `front-qa`, `front-edge`, and `front` deployments. When building and deploying for a specific commit, deploying `front-qa` first and then `front` would result in the `front` deployment using the public environment variables of `front-qa`.

### CODE REVIEW

**Review by fontanierh — COMMENTED** [review]
I don't get it, where is $IMAGE_NAME coming from ?

**Comment by flvndvd** [comment]
> I don't get it, where is $IMAGE_NAME coming from ?

Looks like the part in `cloud-build.yml` was recently updated in https://github.com/dust-tt/dust/pull/7489 by Jules. IMAGE_NAME seems to always have been around.

**Review by fontanierh — APPROVED** [review]
Sorry I missed the part where you are defining IMAGE_NAME at the top of the workflow 👍  
great fix

**Review by JulesBelveze — APPROVED** [review]
Thx 🙏🏼

**Pull request merged**
