### PR TITLE
Display chip for cancelled messages

### PR DESCRIPTION
**Pull request by PopDaph**
Displaying a chip when a message is cancelled, from this discussion: https://dust4ai.slack.com/archives/C050A0S2Z7F/p1696924941531459

Capture d’écran 2023-10-10 à 14 00 17

### CODE REVIEW

**Review by spolu — DISMISSED** [review]
Clash with @philipperolet 

Merge fast :)

**Comment by philipperolet** [comment]
argh! he got me

**Comment by philipperolet** [comment]
> I meant "Clash with @philipperolet's PR" :)

:fearful: incentive to increase velocity :laughing:

**Comment by PopDaph** [comment]
I actually clashed with myself 😅

**Pull request merged**
