### PR TITLE
Assistant V2: UserMessage render markdown

### PR DESCRIPTION
**Pull request by PopDaph**
User message render markdown. 
Using `ReactMarkdown` + introducting "react-syntax-highlighter" library. 
Works with non or partially closed tag

Before: 

Capture d’écran 2023-09-14 à 16 41 42

After: 
Capture d’écran 2023-09-14 à 16 41 30

### CODE REVIEW

**Comment by PopDaph** [comment]
Wait, removed reviewers it's not ready for review, I can improve something!

**Comment by PopDaph** [comment]
Capture d’écran 2023-09-14 à 14 35 07

Updated screenshot!

**Comment by PopDaph** [comment]
still not ready for review, I need to handle propertly when there's only one or two closing backticks!

**Comment by PopDaph** [comment]
@spolu screenshots updated on main post, ready for review 🙏🏻

**Review by fontanierh — APPROVED** [review]
🔥 LGTM

**Review by spolu — APPROVED** [review]
LGTM code-wise

We can merge as is but can we have @Duncid pick the color. My guess is that the gray on top of blue is optimizable? :)

**Comment by PopDaph** [comment]
Awesome! I will see that tomo with @Duncid! 🎉

**Pull request merged**
