### PR TITLE
Make user first name mandatory and use accross the app

### PR DESCRIPTION
**Pull request by PopDaph**
Migrate user > make firstName non nullable now that we have run the migration to fill it. 

Edit `UserType`: 
- Add  `firstName`,`lastName`, `fullName` (a concat of both).
- Remove `name`.

We keep the field name that comes from the oAuth login, but now that the user can override her name, we use `firstName`,`lastName`, `fullName` everywhere in the app over `user.name`.

I love Typescript.

### CODE REVIEW

**Review by spolu — DISMISSED** [review]
Looks good to me :+1: 

Only question is from a user experience, I can't update my First/Last Name ever

cc @Duncid for a solution?

**Comment by Duncid** [comment]
> cc @Duncid for a solution?

Solution is super simple. We'll need to add a member setting page at some point.
It does not seem super urgent though.

**Comment by spolu** [comment]
What's the status here @PopDaph ?

**Comment by PopDaph** [comment]
Didn't want to block Ed who didn't managed to run the migration to set the first and last name on his env -> so not a good reason to be blocked this long. Will merge by EOW

**Pull request merged**
