### PR TITLE
Automated `core` restart

### PR DESCRIPTION
**Pull request by spolu**
New deploy command:
```
./start 2>&1 | tee /var/log/datadog/dust_core.log
```

### CODE REVIEW

**Review by fontanierh — APPROVED** [review]
LGTM, but then how do you kill it ?

**Comment by spolu** [comment]
Ctrl-C works (return 0 exits the until)

**Comment by fontanierh** [comment]
mb, I assumed SIGINT would non-0 exit

**Comment by spolu** [comment]
Maybe it just kills the outter bash script... in any case it works :)

**Comment by fontanierh** [comment]
Wondering what happens if system wants to kill the process (OOM, CPU etc..) or if you have to `kill` it
Anyway, maybe not super important for now

**Comment by spolu** [comment]
If I kill it it restarts, but that's the point :)

**Pull request merged**
