### PR TITLE
Fix apply infra

### PR DESCRIPTION
**Pull request by flvndvd**
## Description

Fixed on oversight from https://github.com/dust-tt/dust/pull/6246 🙈.

### CODE REVIEW

**Review by fontanierh — APPROVED** [review]

**Comment by fontanierh** [comment]
I don't fully remember the `|| true` thing, but I think its correct

**Comment by flvndvd** [comment]
> I don't fully remember the `|| true` thing, but I think its correct

It ensures the script continues without error if the get hpa command fails.

**Comment by fontanierh** [comment]
Ah yes 👍  makes sense

**Comment by fontanierh** [comment]
Doesn't it cause `HPA_EXISTS` to always be truthy though ?

**Comment by flvndvd** [comment]
> Doesn't it cause `HPA_EXISTS` to always be truthy though ?

Nope, it will default to empty string.

**Pull request merged**
