### PR TITLE
enh(multi-actions assistant builder): bury action name in advanced

### PR DESCRIPTION
**Pull request by fontanierh**
## Description

fixes https://github.com/dust-tt/dust/issues/5438

Screenshot 2024-06-05 at 14 15 52

## Risk

N/A

## Deploy Plan

N/A

### CODE REVIEW

**Comment by spolu** [comment]
Can we have it at the top 😬

**Comment by fontanierh** [comment]
@spolu not a gigantic fan but I don't mind

Screenshot 2024-06-04 at 19 03 19
Screenshot 2024-06-04 at 19 03 12

**Comment by spolu** [comment]
I would maybe align it right to make it less "in your face" ?

It's just that action name at the bottom is not super logic, but maybe anything else is bad.

In Instructions we do have the advanced at the top though and it works well?

**Comment by spolu** [comment]
But that likely mean it's a dropdown

**Comment by fontanierh** [comment]
Input in a dropdown not that great though no ?

**Comment by fontanierh** [comment]
I think we should invoke @Duncid

**Comment by PopDaph** [comment]
Maybe same design as the advanced settings we have on the Instructions screen?

**Comment by fontanierh** [comment]
See new screenshot in OP @PopDaph @spolu

**Review by PopDaph — APPROVED** [review]
🙏🏻

**Pull request merged**
