### PR TITLE
fix: Dust app description & visibility update is broken

### PR DESCRIPTION
**Pull request by fontanierh**
## Description

It has been moved under vaults a bit too early (likely by mistake). Updating dust app settings is currently broken

## Risk

N/A

## Deploy Plan

N/A

### CODE REVIEW

**Comment by PopDaph** [comment]
👍🏻

**Comment by spolu** [comment]
Thank you!

Nothing relied on the initial move?

**Comment by philipperolet** [comment]
:+1: LGTM

**Comment by fontanierh** [comment]
> Nothing relied on the initial move?

I don't believe so @spolu

**Pull request merged**
