### PR TITLE
Add memo.connectorId to all workflows

### PR DESCRIPTION
**Pull request by lasryaric**

### CODE REVIEW

**Review by fontanierh — DISMISSED** [review]
LGTM. Is this passed automatically to child workflows ?

**Comment by spolu** [comment]
What's the status here?

**Comment by lasryaric** [comment]
>LGTM. Is this passed automatically to child workflows ?
just tested, they are not being passed :/
I need to forward them everywhere.

**Review by fontanierh — APPROVED** [review]
Looks great thanks for handling the child WFs 🙏

**Pull request merged**
